### ISSUE TITLE
Powers cancelled

### ISSUE THREAD

**Issue by SlimeDog** [MysticCity/MinigamesAPI#104]
Spigot 1.10.2 and the usual constellation of supporting plugins, all latest pulls
MinigamesLib version 1.14.10-20160814.064345
MGFlyingCars version 1.14.10-20160814.071451
MGSnake version 1.14.10-20160814.071708

Despite the fact that no one is playing, there are frequent console/log entries:
[08:26:24 INFO]: Cancelled powerup task.
[08:26:24 INFO]: Use the latest MinigamesLib version to get powerups.

Since this is the latest MinigamesLib version, what else could be the cause?

**Comment by mepeisen** [comment]
should be fixed now. The powerup task is now aborted in a clean way not throwing exceptions.
And no more console spams.
Related to snake, bowbash, splegg
Test with latest snapshot: http://nexus.xworlds.eu/nexus/content/repositories/mce-snapshots/com/github/MCE-Plugins/Minigames-All/1.14.11-SNAPSHOT/Minigames-All-1.14.11-20160819.121318-8-bin.zip
