### ISSUE TITLE
Bad writted language in the spigot page

### ISSUE THREAD

**Issue by altrisi** [MysticCity/MinigamesAPI#105]
In the [SkyWars resource page](https://www.spigotmc.org/resources/skywars.23852/) the name of the language of first video is badwritten. I'm from Spain and it makes me cry. It isn't _Spanisch_, it is _Spanish_.

**Comment by mepeisen** [comment]
oh...
MysticCity is German and - well - forget it.
He will fix it as soon he is online and he will give you comfort. ;-)

**Comment by altrisi** [comment]
Thanks :)

**Comment by altrisi** [comment]
Not changed yet...
It's also in other resources pages.

**Comment by MysticCity** [comment]
......
done
.............
