### ISSUE TITLE
Feature Request: Arrow Trails GUI with permissions

### ISSUE THREAD

**Issue by altrisi** [MysticCity/MinigamesAPI#106]
This is just to add an Arrow Trails GUI to games using bow (SkyWars, OneInTheChamber, BowBash,...). They will need a permission, they can be disabled in the config and the particle names can be selected in the config. Option to add a custom permission per trail

**Comment by mepeisen** [comment]
Typically in minigames lib you can either buy in in the shop (waiting lobby) or you can apply it to a KIT/Class.

The Kits/Classes already can be bound to a permission.

What exactly did you think of?

Maybe that it even works with the existing config.
For example bowbash uses the following default kit items:
    `261:0#ARROW_INFINITE:1#KNOCKBACK:2*1;280:0#KNOCKBACK:4*1;262:0*1`

So the way should be to add a special option to arrows:
    `261:0#ARROW_INFINITE:1#KNOCKBACK:2*1;280:0#POKEMON_TRAIL:0#KNOCKBACK:4*1;262:0*1`

Will this help?

**Comment by altrisi** [comment]
Not exactly. Add a button to select the trail _player_ want to any bow used in the minigame (as an item at the waiting lobby).

**Comment by mepeisen** [comment]
I do not get the point, why we need an additional button.
The items could be present inside the shop.

The shop items already can
* be enabled/disabled
* be configured through config (shop.yml)
* optionally require money through vault
* optionally require a permission

All I would have to do is to add the special trails animation (maybe through additional configurations or hard coded).

**Comment by mepeisen** [comment]
Can you share the code? Or do you have an isolated plugin that can be used from minigames-lib? imilar to crackshot.
Would be nice for admins to use this feature in shop items or kits.

**Comment by ToHindahl** [comment]
also ich spreche Deutsch und es ist eher so eine Api und ich versuche sie Gerade in die MinigamesLib einzubauen

**Comment by mepeisen** [comment]
ok. super.
com.comze_instancelabs.minigamesapi.util.Util.parseItems(String) ist die richtige Stelle dafür. Wenn Fragen sind, einfach fragen.

**Comment by ToHindahl** [comment]
Wenn das Benutzt wird will ich informiert und Gennant werden!
[Trails.zip](https://github.com/MysticCity/MinigamesAPI/files/426610/Trails.zip)

**Comment by mepeisen** [comment]
Du wirst logischerweise als Autor in den Sourcen stehen. Und als Contributor in der plugins.yml.

**Comment by ToHindahl** [comment]
in der Trails.zip ist eine Classe für die 1.8.8 mit der man wenn man die permission arrow.trails hat Trail arrows schießt

**Comment by MysticCity** [comment]
Werden wir so nicht nutzen Danke.
Aber wir können so eine Option gerne mit einbauen

SPÄTER

**Comment by altrisi** [comment]
Closing as stale
