### ISSUE TITLE
Chunk Bugged

### ISSUE THREAD

**Issue by tigierrei** [MysticCity/MinigamesAPI#111]
When i join the lobby and the arena of every MG plugins, every chunk where i stand became bugged and i can't move. No idea why. I currently have installed the latest MinigamesLib.
I'm using PaperSpigot 1.9

**Comment by tigierrei** [comment]
I have read on another topic about the same problem, but I can't find a solutions.
I'm using multiverse, but sign,lobbies and arenas are in the same world.
Also F3+A doesn't fix the bug. The only way to fix the chunk is leave and reconnect to server.
Any idea?

**Comment by mepeisen** [comment]
Do you use 1.14.10 oder the latest 1.14.11 snapshot?

**Comment by tigierrei** [comment]
1.14.10 . I will try now to use the snapshot

**Comment by tigierrei** [comment]
Still have the same problem. I used that snapshot: http://nexus.xworlds.eu/nexus/content/repositories/mce-snapshots/com/github/MCE-Plugins/MinigamesLib/1.14.11-SNAPSHOT/MinigamesLib-1.14.11-20160814.083920-1.jar
Is it correct?

**Comment by mepeisen** [comment]
no, ist too old. I fixed it 2 days before.
Simply use the newest from today 12:04
http://nexus.xworlds.eu/nexus/content/repositories/mce-snapshots/com/github/MCE-Plugins/MinigamesLib/1.14.11-SNAPSHOT/MinigamesLib-1.14.11-20160819.120438-9.jar

**Comment by tigierrei** [comment]
Fixed, thank you!

**Comment by mepeisen** [comment]
closed. the problems with multiverse and inventory will be commented in the other bug.
