### ISSUE TITLE
MobEscape: Make dragon destroy blocks in sphere form.

### ISSUE THREAD

**Issue by YouGamePlayHD** [MysticCity/MinigamesAPI#125]
I have a suggestion for MobEscape. To make it seem more realistic, could you change the form of block destruction from cubic to sphere? The destruction-radius would then represent the radius of the destruction sphere.

**Comment by mepeisen** [comment]
I did some experiments with dragon/wither animation. But something is still going wrong. It is not easy to make the animations "realistic". Will be part of 1.14.15.

**Comment by mepeisen** [comment]
added new config: destroy\_mode
Set it to "sphere" to let the wither/dragon destroy in sphere form.

Latest snapshot can be found at http://www.minigameslib.de/downloads_en.php
It will be build within the next two hours.
