### ISSUE TITLE
MobEscape: Blöcke mit Partikeln, wenn sie zerstört werden

### ISSUE THREAD

**Issue by YouGamePlayHD** [MysticCity/MinigamesAPI#146]
Hier ist eine neue Verbesserung für MobEscape (das Spiel, auf das ich mich momentan voll konzentriere):
Wie auf Mineplex werden Blöcke weggeworfen. Das ist toll, aber einen kleinen Unterschied gibt es noch: Auf Mineplex werden die Blöcke, die der Drache gerade zerstört, mit den jeweiligen Abbaupartikeln versehen. Könnte man das auch im Plugin möglich machen? Es ist nur eine kleine und unbedeutende Verbesserung, würde die Performance des Spiels aber steigern.

**Comment by mepeisen** [comment]
I did some experiments with dragon/wither animation. But something is still going wrong. It is not easy to make the animations "realistic". Will be part of 1.14.15.

**Comment by mepeisen** [comment]
fixed

Latest snapshot can be found at http://www.minigameslib.de/downloads_en.php
It will be build within the next two hours.
