### ISSUE TITLE
version numbers inconsistent

### ISSUE THREAD

**Issue by SlimeDog** [MysticCity/MinigamesAPI#147]
New released versions, per jar file names and release pages: 1.14.11
Internal versions: 1.14.12

Please keep external and internal version numbers consistent.

**Comment by mepeisen** [comment]
Seems that my release build is broken (whatever).
I will Review the release build for the next release. The next version will be release 1.14.13.

**Comment by mepeisen** [comment]
fixed. https://github.com/MCE-Plugins/MInigames-All/releases/tag/v1.14.13
