### ISSUE TITLE
Horse Race Plugin

### ISSUE THREAD

**Issue by EliasRipley** [MysticCity/MinigamesAPI#156]
Copying comment made on the HorseRace plugin at request of Author.

Version: 1.14.11
Start Line Problem. Simply didn't work. When the countdown from 10 finished, the horses went flying high into the air to random locations... far from the arena. The game did end after we raced back to the finish line though... =D

**Comment by mepeisen** [comment]
Did you set the arena bounds correctly? Sometimes this happens while running outside the arena. The plugins trys to kick you back and this may go very wrong

**Comment by mepeisen** [comment]
Unable to reproduce this issue.
Closed because of missing response from reporter.
