### ISSUE TITLE
[BUG] No resources BedWars

### ISSUE THREAD

**Issue by UDOgaming** [MysticCity/MinigamesAPI#157]
whenever I place down a resources block such as clay, iron, and gold blocks no resources will show up. I might just be miss interpreting it but an answer would be great. Thanks!

**Comment by mepeisen** [comment]
Did you set the arena bounds first? The arena bounds are covering the resource spots?

**Comment by UDOgaming** [comment]
Ok I got it to work! sorry for wasting your time. I didn't do /bw arenasave

**Comment by mepeisen** [comment]
no problem. thanks for response
