### ISSUE TITLE
[BUG] BedWars

### ISSUE THREAD

**Issue by UDOgaming** [MysticCity/MinigamesAPI#162]
I noticed when there is more then 3 (In my case) the GUI Randomly closes sometimes. also, the teams are buggy AF so if you can't fix it at the moment can you please make a way to disable the hub GUI? It also has a huge issue where it crashes the game half the time anyone wins... But other than that keep up the good work!

**Comment by HyperBlueCore** [comment]
more than three what players or what

**Comment by mepeisen** [comment]
You are talking about the villager trading GUI?

> the teams are buggy AF

What exactly is buggy?

> make a way to disable the hub GUI?

What GUI should we disable?

> It also has a huge issue where it crashes the game half the time anyone wins...

Are there any console errors when the game crashed? Any stack trace or similar things you can add here?

**Comment by mepeisen** [comment]
Closed.
If you still have a problem please answer.
