### ISSUE TITLE
[MGDeathrun] Players die before they hit the low boundary

### ISSUE THREAD

**Issue by logicalPolaris** [MysticCity/MinigamesAPI#167]
My bounds are very high and low in the 'y' segment, but for some reason, instead of dying at y: 90, players die at y: ~138, before they hit the last platform.
I've tried setting   die_below_bedrock_level to true and false, but both don't do anything.

Any ideas?

    bounds:
      low:
        world: minigames
        location:
          x: 38.71282240894799
          y: 90.21741168861061
          z: 536.785574389396
          yaw: -215.56015
          pitch: -47.499603
      high:
        world: minigames
        location:
          x: 2.6076552772039054
          y: 177.95774726651197
          z: 496.6723286644143
          yaw: -16.479424
          pitch: 88.50156

**Comment by mepeisen** [comment]
In next version you can set numeric values instead of only true/false
see #126.
