### ISSUE TITLE
[MGDeathrun] Some blocks not regenerating at end of game

### ISSUE THREAD

**Issue by logicalPolaris** [MysticCity/MinigamesAPI#168]
Sorry for all of these issue posts. I don't mean to be a nuisance.

Anyways, at the end of a Deathrun game, I go back and some of the blocks that fell are not regenerated at the end of the match.

Is this because there is another plugin that is messing with it, or is this a common bug?

![screenshot_37](https://cloud.githubusercontent.com/assets/11083026/19017673/b55c9fb4-87f7-11e6-958f-ae4e3b5f4dd7.png)
(Example of blocks falling that were not removed after the game)

Thank you in advance!

**Comment by mepeisen** [comment]
maybe the same bug as #162.
I am currently trying hard to fix it.
What version of lib/deathrun are you using?

**Comment by logicalPolaris** [comment]
I'm running 1.14.12-20160918.123620 (basically the latest dev build I could find.)

**Comment by mepeisen** [comment]
Please retry with 1.14.13
https://github.com/MCE-Plugins/MInigames-All/releases/tag/v1.14.13

**Comment by mepeisen** [comment]
no more response. If the problem is not solved please reopen again.
