### ISSUE TITLE
Minimaps Skywars and Deathrun not regenerated fully

### ISSUE THREAD

**Issue by obiku19** [MysticCity/MinigamesAPI#169]
All,

I have issues with skywars not resetting (renerating) the islands after the game ends.
Ingame placed blocks are still on the islands, which mostly gives an advantage on a new game...

Minigameslab version is 1.14.11, my MGSkyWars version is also 1.14.11

A simular issue I have with MGDeathrun (v1.14.11). Also here the map doesn't get a total reset. And another issue is... On one map I have multiple floors, unfortunately the game ends before the player passes the low bound.....

**Comment by mepeisen** [comment]
First check if your arena bounds are including all your islands.
We have two other bugs, #168 and #152.
Maybe you can send me a worldedit of your arena to mep_eisen@web.de
I will try to reproduce it.

**Comment by obiku19** [comment]
Thanx for the reply, I uploaded both schematics to you e-mail account (Skywars schematic and DeathRun schematic)
My high and low bounds in each game include the entire schematic. For SkyWars, the left behind blocks are being deleted after doing a manual reset of the game /sw reset [gamename]
DeathRun is something different, no matter what I do (set a worlguard region with infinity allow), the player that sinks thru the floor loses, even if he didn't pass the low bound.

**Comment by obiku19** [comment]
Ohw, did find another bug too, but I have seen a post on it in #152.
My shematic has some pools of water in them, if the water runs of the island and the game ends a trail of water just below the lower bound remains present...

**Comment by mepeisen** [comment]
For death run and the loses please see #126
I will try to fix lava and water during smart reset.

**Comment by mepeisen** [comment]
I played your deathrun arena with my bots several times. On spigot 1.10.2 all the blocks get restored.
Do you have a screenshot of a broke arena after playing?

The lava/water problem is identified. Smart reset does not catch all the physics events. I am working on it.
Please retry with latest snapshot if the other problems are gone. 
http://nexus.xworlds.eu/nexus/content/repositories/mce-snapshots/com/github/MCE-Plugins/Minigames-All/1.14.12-SNAPSHOT/Minigames-All-1.14.12-20161016.083234-5-bin.zip

**Comment by obiku19** [comment]
Islands got restored on SkyBlock, but after the game ends, no one can enter it again.... :/
I have 2 skywars games, both were not accessible after game end.

**Comment by mepeisen** [comment]
Please retry with latest release.
https://github.com/MCE-Plugins/MInigames-All/releases/tag/v1.14.13

Are there any errors in console after game end? What color has the join sign?

**Comment by mepeisen** [comment]
closed because of no response
