### ISSUE TITLE
Joining And Loading MobEscape

### ISSUE THREAD

**Issue by MMCraftin** [MysticCity/MinigamesAPI#170]
I Can't Do Joining In All Version And In Latest Version Plugin Doesn't Even Load
I am Running Spigot 1.8.8 And MinigamesLib-1.14.11

**Comment by mepeisen** [comment]
any errors in console?

**Comment by MMCraftin** [comment]
error nor loading comes up in console

**Comment by mepeisen** [comment]
please retry with https://github.com/MCE-Plugins/MInigames-All/releases/tag/v1.14.13
If you still have issues please contact me at mep_eisen@web.de and send me your server data. I would like to watch it live.

**Comment by mepeisen** [comment]
closed for no response :-(
