### ISSUE TITLE
Game ends but some players stay bugged like they are in the minigame

### ISSUE THREAD

**Issue by NocturneCZ** [MysticCity/MinigamesAPI#172]
I dont know if this applies to all minigames, or just spleef, but we came across a bug, where me and my friend were playing spleef, he died, I won, game ended, I was fine, but he still had the minigame inventory and even tho he had creative, he couldnt place blocks, like he was still in the minigame. I tried to stop the arena with command, but he was still bugged. Even after relog, he was still bugged. PLEASE FIX ASAP

**Comment by mepeisen** [comment]
Sry for the late answer.
Did you get any errors in console while this happens?
Can you retry with latest snapshot? https://github.com/MCE-Plugins/MInigames-All/releases/tag/v1.14.13

**Comment by mepeisen** [comment]
closed because of no response
