### ISSUE TITLE
1.11 support.

### ISSUE THREAD

**Issue by TheIntelloBox** [MysticCity/MinigamesAPI#173]
Hello,

Could you add 1.11 support ? :D 

Thanks ! :D

**Comment by mepeisen** [comment]
Already on my list ;-)

**Comment by TheIntelloBox** [comment]
Oh yeah. :) When will you update to 1.11, do you think ? :D

**Comment by mepeisen** [comment]
I am still testing. There were some deep changes affecting one or two games. Maybe tomorrow, maybe wednesday. But I don't think it will take too long.

**Comment by TheIntelloBox** [comment]
Okay. :D

**Comment by mepeisen** [comment]
Please check with latest snapshot. Please give me feedback which games you tested . I will do some more tests before releasing 1.14.14
http://nexus.xworlds.eu/nexus/content/repositories/mce-snapshots/com/github/MCE-Plugins/Minigames-All/1.14.14-SNAPSHOT/

**Comment by TheIntelloBox** [comment]
Okay. :D

**Comment by TheIntelloBox** [comment]
Hello,

See it : http://hastebin.com/fepivotafa.vbs

Thanks ! :D

**Comment by mepeisen** [comment]
not caused by minigames.
Google says this is should caused by a plugin "GitanTrees" or similar. Deactivate it and wait for it's 1.11 Migration.

**Comment by TheIntelloBox** [comment]
Okay, it's works fine !

**Comment by mepeisen** [comment]
closed
