### ISSUE TITLE
MGSplegg Permissions Setup didnt work!

### ISSUE THREAD

**Issue by Creek22** [MysticCity/MinigamesAPI#174]
After talking to MysticCity he told me to create a Ticket...

I tried now over 5 Hours to set the Permission to force start a MG Splegg arena with /start.

minigames.core
minigames.core.start
minigames.core.*
minigames.*
noch
minigames.splegg.start
minigames.splegg.*
minigames.mgsplegg.*
minigames.spl.*

These are the nodes i tried after i readed the wiki. If they are wrong, then the Wiki is really missunderstandable and should be corrected. 

Cant find the mistake with the nodes...

**Comment by Creek22** [comment]
Sometimes you only need to sleep about it... 

#ancient.splegg.start

**Comment by mepeisen** [comment]
or have a look at our wiki: https://github.com/MysticCity/MinigamesAPI/wiki/Permissions
But you are right. It may be confusing, see the last chapter on the wiki page.
I will reopen it to review the wiki page.

**Comment by Creek22** [comment]
Yeah thats true... The last Chapter on the Wiki is really confusing... Took me 5 Hours and a night to sleep over it to get it, that the permission prefix is not automatically "minigames." and i need to control my MinigamesLib config to get it...

**Comment by mepeisen** [comment]
wiki was updated
