### ISSUE TITLE
HorseRacing not working on 1.11

### ISSUE THREAD

**Issue by skilledpt** [MysticCity/MinigamesAPI#177]
Hello mate, MGHorseRacingPlus isnt working for 1.11 can u update it please? I love this puglin

**Comment by mepeisen** [comment]
Did you test with latest snapshot?

**Comment by mepeisen** [comment]
fixed in 1.14.14.
Please retry with newest snapshot or wait for the release.
Download at http://www.minigameslib.de/downloads_en.php
