### ISSUE TITLE
Scoreboard displays wrong arena name

### ISSUE THREAD

**Issue by SlimeDog** [MysticCity/MinigamesAPI#178]
Environment: Spigot 1.10.2 (last pull), MinigamesLib 1.14.13, MGSnake 1.14.13.

I have two MGSnake arenas, SmallSnake and LargeSnake, listed in that order in _arenas.yml_ 

> mainlobby:
...
arenas:
  SmallSnake:
...
    displayname: SMALL SNAKE
...
    showscoreboard: true
  LargeSnake:
...
    displayname: LARGE SNAKE
...
    showscoreboard: true

The _messages.yml_ file contains

>   ...
    scoreboard:
      title: '&4<arena>'
      lobby_title: '&4&l<arena>'
...

In both arenas, the scoreboard displays **SmallSnake**. The scoreboards appear to be correct otherwise, displaying differently for the two arenas which have different player limits.

Interestingly, changing the order of the list in _arenas.yml_ does not change the outcome.

My Spigot 1.11, MG 1.14.14 server is down for re-configuration, so I cannot verify with the update at present. Perhaps tomorrow, if you do not have sufficient information to isolate the issue.

**Comment by mepeisen** [comment]
fixed in 1.14.14.
Please retry with newest snapshot or wait for the release.
Download at http://www.minigameslib.de/downloads_en.php

**Comment by SlimeDog** [comment]
Verified with Spigot 1.11.2 latest, MG 1.14.14-SNAPSHOT-20161231
