### ISSUE TITLE
[MGSkyWars] Error while trying to enter the arena. (Internal Error)

### ISSUE THREAD

**Issue by Fencery** [MysticCity/MinigamesAPI#184]
Hello! I get this error when I try to join a SkyWars game. Both MinigamesLib and MGSkyWars are up to date (I got it from the spigot website. Are there any snapshots available?) In-game I receive a piece of text in light red letters. An internal error occurred while attempting to perform this command. Thanks for all your help!

Server Version: Spigot 1.11.2
Client Version: Optifine 1.11.2
http://pastebin.com/6z3TzYfb

Plugins:
-WorldEdit, WorldGuard, PermissionsEx, Vault, Votifier, Citizens, EssentialsX, EssentialsXChat, EssentialsXGeoIP, EssentialsXProtect, EssentialsXSpawn, EssentialsXXMPP, PlotSquared, Enjin, Multiverse Core, Multiverse Inventories, Multiverse Portals, Holographic Displays, MinigamesLib, MGSkyWars.

**Comment by mepeisen** [comment]
please use the latest snapshot for 1.11 support.
http://www.minigameslib.de/downloads_en.php
