### ISSUE TITLE
Splegg/Spleef: Game ends when going trough the first platform 

### ISSUE THREAD

**Issue by LittlePapaJohn** [MysticCity/MinigamesAPI#186]
The tutorials show 3 platforms for example below eachother. After falling through the first platform the player already loose the game (3 blocks down). Perhaps this is meant to be but I doubt it. If it is then please add to future feature list.
Running: 2017-01-01 build (also running latest versions: Vault, worldedit and multiverse core) on Spigot 1.11.2 latest build
Bounds set well below and above the arena. No error messages recieved on the server.

**Comment by SlimeDog** [comment]
Environment: Spigot 1.11.2 with Spleef/MG 1.14.14-20161231, WE/EG, Vault, MV all latest.

I have a two-level arena, 4 blocks between layers, each of which is one block high. Spawnpoints are on the upper level. Bounds are set +3Y above the upper layer and -5Y below the lower layer (to incorporate the lava pool in which the losers die).

This is a test server, so no players. However, I started the game (join via sign, then **/sp start <arena>**), dropped through a hole to the lower level (to simulate losing the floor to opponents). I did not die or lose the game, and continued to play.

**Comment by LittlePapaJohn** [comment]
Dear SlimeDog, Thanks or the information. This type of feature is not available in the config nor arena set-up so it is pretty peculiar it happens. 
I also run this on the test server on my normal computer with similar plugins you have. This issue might perhaps be gone when uploading to another server.

**Comment by mepeisen** [comment]
It is available in config but it is hidden.
In 2.0 the behaviour will be very different. There will be Special zonses you can create for "winning" or "losing".

Look at the configuration value of "config.die_below_bedrock_level"
It may hold true/false or a numeric value with following meaning:

true lets Players lose if they are 100 blocks below spawn.
false lets Players lose if they are 4 blocks below spawn.
A numeric value can be set to any other value.

Sorry if this was confusing. This was original behavior InstanceLabs implemented. I do not know why he does it. There were Bugs in the past so I decided to rewrite to accept numeric values. This was a compromise to not break compatibility.

**Comment by mepeisen** [comment]
and yes, if someone falls out of the arena bounds he will lose too.

**Comment by LittlePapaJohn** [comment]
Thanks, I found it. Looking forward for the new versions, sounds great.

**Comment by mepeisen** [comment]
V2 is a complete rewrite. It will be spread up into a core library handling most of the stuff outside minigames and the mingames itself.
It ships with an (optional) forge mod for client guis, administration helpers etc.
Some random Image preview: http://www.minigameslib.de/mclib/img/gui-preview.jpg

**Comment by LittlePapaJohn** [comment]
I will wait with a on-line server upload then until you finished the new version. I currently created arenas for the majority of games. If you want me to test a few minigames on Spigot with the new versions then let me know.

**Comment by mepeisen** [comment]
You are welcome to test new versions and reports bugs here :-)
