### ISSUE TITLE
CTF 

### ISSUE THREAD

**Issue by PetteRed65** [MysticCity/MinigamesAPI#189]
Can you add a capture the flag mode where the player need to get the other team's flag by destroying it and get point by taking it in his flag area? Like cubecraft's blockwars

**Comment by mepeisen** [comment]
a classic ctf (get flag and return to home base) is already planned as new game. Having Scouts, runners, fighters etc. If you have a special wish on the game mode of ctf you can place it in the following issues:
https://github.com/MysticCity/MinigamesAPI/issues/132
