### ISSUE TITLE
1.11.* please

### ISSUE THREAD

**Issue by anemul** [MysticCity/MinigamesAPI#190]
Feature Request Please update minigameslib , deathrun and skywars to 1.11.* please please puhlease

**Comment by mepeisen** [comment]
it is already there.
http://www.minigameslib.de/downloads_en.php
Download version 1.14.14

MysticCity will update spigot this weekend.

changelog http://git.mystic-city.de:3000/Mystic-City/MinigamesLib/src/master/changelog.md
