### ISSUE TITLE
SkyWars - Problem with TabMenu

### ISSUE THREAD

**Issue by degzm** [MysticCity/MinigamesAPI#194]
Well, i want to have the coloredTags plugin, and skywars, but there is a problem.
The problem is, when i enter a game, the tab color dont show, it erases, but if i make a relog, it shows again fine.
Theres a way to deactivate the tabcolor, and scoreboard?
Or just the tab menu?
Its very annoying.

Shows Correctly...
![image](https://cloud.githubusercontent.com/assets/14362858/21954007/5f0f57d0-da0b-11e6-9c75-580fcde9f650.png)

But, entering in game, just disappears 
![image](https://cloud.githubusercontent.com/assets/14362858/21954010/7dc02d3a-da0b-11e6-9240-1ba2e4d8b250.png)

This only happend when i install the plugin :(

**Comment by mepeisen** [comment]
Can you attach a link to the plugin and (if needed) your plugin config of coloredtags?

**Comment by degzm** [comment]
This is Ctags plugin: https://dev.bukkit.org/projects/colored-tags
And the config file are this, is small haha:
![image](https://cloud.githubusercontent.com/assets/14362858/21954565/5b90b022-da1a-11e6-9f80-d8d1d7509be4.png)

And how you can see, the plugin webpage says that Ctags, can conflict whit another plugin wich uses
the scoreboard.

**Comment by degzm** [comment]
Oh, and iam using the tablist, but works fine.
![image](https://cloud.githubusercontent.com/assets/14362858/21954592/104433b8-da1b-11e6-884f-eb4c9927eaf3.png)

**Comment by mepeisen** [comment]
You will now find a new config variable: "use\_spectator\_scoreboard"
As far as I see the spectators management is the only situation where the scoreboard teams are influenced. Setting it to false should help to keep your tab menu stable.

Latest snapshot can be found at http://www.minigameslib.de/downloads_en.php within the next two hours.
