### ISSUE TITLE
Development API - Wiki needs updating / minor typos

### ISSUE THREAD

**Issue by Emalton** [MysticCity/MinigamesAPI#195]
https://github.com/MysticCity/MinigamesAPI/wiki/First-Minigame
Under the example code snippet, @Override was forgotten above onEnable. Also the setupAPI method below is deprecated.

    public void onEnable() {
        api = MinigamesAPI.getAPI().setupAPI(this, "my_minigame");
    }

**Comment by Emalton** [comment]
Where can I find a good updated example of this API being used? The documentation is very outdated. :(

**Comment by mepeisen** [comment]
@Override is an optional annotation. Although it may be good design to use it and even to let compilers report if it is missing.

I may update it if I have time.

Anyhow the API in Version 1.x won't ever be well documented. I am currently working on a complete rewrite. The new core library (mclib) is published in it's first alpha version. https://www.spigotmc.org/resources/mclib.34556/

There is a link into manual at the end of the description.

I am experimenting with OneInTheChamber and maybe there will be soon a first alpha version of this minigame using the new lib.

**Comment by Emalton** [comment]
Awesome, adding it as we speak.

YOU ROCK THANKS!
