### ISSUE TITLE
Conquer lag

### ISSUE THREAD

**Issue by Owenftw** [MysticCity/MinigamesAPI#198]
Whenever the game begins, server TPS drops from 20 to around 17.5
It also causes a small lag spike every time a team takes over a checkpoint (The last wool on a checkpoint takes a few seconds to change, once it changes the firework sets off and people are sent back to the location they was at a few seconds ago)

**Comment by mepeisen** [comment]
Please check the latest snapshot till next weekend. I fixed lags caused by scoreboard updates. Area there any additional problems and lags?

Latest snapshot can be found at http://www.minigameslib.de/downloads_en.php within the next two hours.

**Comment by mepeisen** [comment]
*closed* If this does not help please respond. I will reopen the issue.
