### ISSUE TITLE
DeathRun & Splegg console spam

### ISSUE THREAD

**Issue by Owenftw** [MysticCity/MinigamesAPI#200]
I'm sure this is the same for all the plugins that require blocks to be reset.

After a match of deathrun or Splegg ends, it spams the console: https://s29.postimg.org/438fg1zrb/spam.png
https://s23.postimg.org/6lljdkyor/spleggspam.png

I'm also wondering if you could hook into FastAsyncWorldEdit and use that to reset the blocks, My servers TPS drops from 20 to 19.5 while resetting arenas. (this is just on a test server with 2 players so I can see it causing lag on a real server)

**Comment by mepeisen** [comment]
fixed in latest snapshot. Will now only spam if debug config option is set to true
Latest snapshot can be found at http://www.minigameslib.de/downloads_en.php within the next two hours.
