### ISSUE TITLE
MGsnake issues

### ISSUE THREAD

**Issue by EddiesLife247** [MysticCity/MinigamesAPI#202]
2 errors have come to light when playing MGSnake on my server

Spawn locations can sometimes have 2 people inside them.
Players can only see floating boots, and no wool being placed behind them.

**Comment by mepeisen** [comment]
Some questions on this bug.

> Spawn locations can sometimes have 2 people inside them.
How many players played? How many spawns? Can you post the arenas.yml file?

> Players can only see floating boots, and no wool being placed behind them.
Do you have additional plugins that may cancel the entity spawns? worldguard or something similar?

**Comment by mepeisen** [comment]
closed because no response
