### ISSUE TITLE
Missing method

### ISSUE THREAD

**Issue by Rocologo** [MysticCity/MinigamesAPI#203]
Hi I'm the developer of [MobHunting](https://www.spigotmc.org/resources/mobhunting.3582/). I'm trying to add support / hook into MinigamesAPI.

I have succeded to make the hook and can get 

MinigamesAPI.getAPI()

But I need a method 

MinigamesAPI.getAPI().isPlayingAMiniGame(Player); which return true if the player has joined a game and false if not.

I hope you will make this method for me, so I am able to add support for your plugin?

Kind regards
Rocologo

**Comment by Rocologo** [comment]
I see you accepted the feature request for 1.14.15, please let me know when I can start testing on a snapshot.

**Comment by mepeisen** [comment]
version 1.14.15 and above: check with getArenaForPlayer(playerName) != null
version 2 and above: MinigamesLibInterface.instance().getPlayer(uuid).getArena() != null

Latest snapshot can be found at http://www.minigameslib.de/downloads_en.php within the next two hours.
