### ISSUE TITLE
MinigamesLib Bungee integration

### ISSUE THREAD

**Issue by xXSchrandXx** [MysticCity/MinigamesAPI#204]
In your newest MinigamesLib version is the MinigamesLib-Bungee integrated?

If yes could you explain how the new format for the signs is? The old doesn't work for me.

**Comment by mepeisen** [comment]
i assume you got it wirking?
Reopened because of missing wiki page.

**Comment by xXSchrandXx** [comment]
I used the wrong format, I wrote [MGLib] instead of MGLib

**Comment by mepeisen** [comment]
Wiki page: https://github.com/MysticCity/MinigamesAPI/wiki/Bungee-Support
