### ISSUE TITLE
MinigamesLib Party-System and BungeeCord

### ISSUE THREAD

**Issue by xXSchrandXx** [MysticCity/MinigamesAPI#208]
Hi, I do have Bungeecord and your newest MinigamesLib on my lobby server. How do I manage that the players in a party will get teleported to the minigame Server if the owner of the party is joining a minigame server?

**Comment by mepeisen** [comment]
It does not yet work over bungeecoord.

**Comment by mepeisen** [comment]
fixed.

This may lead to problems if the party is to big and not all players can join the game. In 2.0 I will solve this by a new feature (waiting queues). For the moment advice your players to only use small parties over bungeecord.

Latest snapshot can be found at http://www.minigameslib.de/downloads_en.php
It will be build within the next two hours.
