### ISSUE TITLE
Just a question.

### ISSUE THREAD

**Issue by hermitplays** [MysticCity/MinigamesAPI#214]
So I was wondering how do I put custom stuff in chests? When I do they just disappear. Am I doing something wrong? please respond.

**Comment by mepeisen** [comment]
What exactly are you planning to do? Did you edit configuration files? Did you try it in game? Which game?

**Comment by hermitplays** [comment]
I try to add custom stuff to the chests on skywars but they just disappear.

**Comment by mepeisen** [comment]
This is wanted behaviour.
Try to edit "chests.yml" of folder plugins/MGSkyWars.
There you will find the items packed into the chests.

To add an item that is always present in each chest simply add it to every items config line.
For example to add 30 dirt you will have to change the default config to:
3*30;5*64......
id #3 is dirt. See ids at the following list: http://minecraft-ids.grahamedgecombe.com/

**Comment by mepeisen** [comment]
*closed* If this does not help please respond to the issue and I will reopen it.
