### ISSUE TITLE
BedWars/Autobalance teams

### ISSUE THREAD

**Issue by PantallazoAzul** [MysticCity/MinigamesAPI#215]
**Hello!**
I love this plugin, and thank you for making it for free 😄 
But I have a problem: When all players in an arena join to only one team, the game starts anyway and just with players in that team:
Example: 4 players join to Red Team. So other teams have 0 players while Red Team have 4.
So it's something weird 👅 

Thank you again! ❤️ And sorry for my bad english.

_I'm using git-Spigot-af8198d-8cc5958 (MC: 1.10.2) with ViaVersion plugin and latest SNAPSHOTS of MinigamesLib and others._

**Comment by mepeisen** [comment]
fixed. Bedwars will now report any unbalanced team. If the lobby countdown ends without having balanced teams the arena will not start. Once a player selects a new team the lobby countdown will restart.

Latest snapshot can be found at http://www.minigameslib.de/downloads_en.php
It will be build within the next two hours.

**Comment by PantallazoAzul** [comment]
Thanks man, you are awesome, I was trying to make my own modification but you did it first :P thank you! (I'm new with programming) 👍

**Comment by mepeisen** [comment]
You are welcome to share any idea or any piece of code :-)

**Comment by PantallazoAzul** [comment]
Thank you :-) what I really need is to translate hard coded strings to spanish and test some lines of code in BedWars but... I'm new in programming so all I do is try and error 😆

**Comment by mepeisen** [comment]
I moved the user readable strings to messages.yml.

Latest snapshot can be found at http://www.minigameslib.de/downloads_en.php
It will be build within the next two hours.
