### ISSUE TITLE
BungeeCord signs, and leaving the server.

### ISSUE THREAD

**Issue by Tim-NL** [MysticCity/MinigamesAPI#217]
Hello, 
I'm trying to join with the BungeeCord feature, but it doesn't count down when you just quit / leave the server instead of typing /l or cliking the block. 

Video, to make it more clear: https://www.youtube.com/watch?v=0IB1oNDUvtE

Hope you can fix it :)

EDIT: I think its because the server can't send pluginMessages when everybody is gone. Perhaps you could implement something like; Checking the number of players on the "games" server every minute from the server that has the signs. And if there is nobody online, just set it to "Ready" and 0/x players. I can change my /hub command to a local one (instead of a proxy side command), that makes the player leave the game first, but that won't solve clicking on "disconnect". 

Thanks.

**Comment by mepeisen** [comment]
It is correct that PluginMessages are sent through online players. I already got some strange problems in my new stream in 2.0 but there will be some oher solution for this problem.
I will check if your suggestion works.

**Comment by mepeisen** [comment]
fixed

Latest snapshot can be found at http://www.minigameslib.de/downloads_en.php
It will be build within the next minutes.

*closed* If this does not help please respond. I will reopen the issue.
