### ISSUE TITLE
GunGame: Modify Scoreboard

### ISSUE THREAD

**Issue by YouGamePlayHD** [MysticCity/MinigamesAPI#218]
Hey,
is it possible to modify the scoreboard of GunGame?
I'm coding for a French server and I need to change the names.
Thanks in advance.

**Comment by mepeisen** [comment]
fixed in latest snapshot. You will now find 4 new entries in messages.yml starting with "sb_".
Latest snapshot can be found at http://www.minigameslib.de/downloads_en.php within the next two hours.

**Comment by YouGamePlayHD** [comment]
I can't find the entries. Are they in MGGunGame/messages.yml?

**Comment by YouGamePlayHD** [comment]
I can't change it. It keeps displaying the old stuff. Do I need to acctivate something in the config?

**Comment by YouGamePlayHD** [comment]
The title, too? :D

**Comment by mepeisen** [comment]
The player sub title can be influenced via config sb\_name\_level

**Comment by YouGamePlayHD** [comment]
No, was just my own stupidity. I accidentally downloaded the wrong snapshot -.-
Thanks for asking ;)

**Comment by mepeisen** [comment]
I will have a close look this weekend.

**Comment by YouGamePlayHD** [comment]
Thank you ;)

**Comment by mepeisen** [comment]
changed. see sb_title config

Latest snapshot can be found at http://www.minigameslib.de/downloads_en.php
It will be build within the next two hours.
