### ISSUE TITLE
Permissions

### ISSUE THREAD

**Issue by CoppyPaste** [MysticCity/MinigamesAPI#219]
It could be a stupid question but where is the permissions for the Splegg & Speef plugin. Whenever I click on the perms tab on the Splegg page it opens up the minigameslib's permissions and I can't really understand those perms.

**Comment by PantallazoAzul** [comment]
I think that permissions are in general, por example: You have ancient.[game].start, but you replace [game] with the internal name of Splegg, ancient.splegg.start

**Comment by mepeisen** [comment]
you are right.
Please see the following wiki page: https://github.com/MysticCity/MinigamesAPI/wiki/Permissions

Any further questions?
