### ISSUE TITLE
How do you make leaps stronger/weaker in strength..

### ISSUE THREAD

**Issue by StarMonkeyHD** [MysticCity/MinigamesAPI#22]
I need some help with making the leaps on every kit stronger/weaker.

**Comment by mepeisen** [comment]
You mean the leaping potion? http://www.minecraftinfo.com/leapingpotion300.htm
Do you create it programmatically or via config?

**Comment by StarMonkeyHD** [comment]
No, I mean like when u use the axe to leap.. Change how far u leap and that kind of stuff.

**Comment by StarMonkeyHD** [comment]
MGMobEscape

**Comment by StarMonkeyHD** [comment]
If u would like to join the server I could show you?

**Comment by mepeisen** [comment]
please send me the data to mep_eisen@web.de

**Comment by mepeisen** [comment]
Please see https://github.com/instance01/MinigamesAPI/wiki/Default-Config-and-Item-Markup for details how to configure the effect power on items.
Item ids of the axes:
258 (iron)
271 (wooden)
275 (stone)
279 (diamond)
286 (gold)

The iron axe is currently hard coded. Please check if you can change it.
For example to "275#JUMP:1*1" or "275#JUMP:4*1"
Format: <item-id>#<effect>:<power>*<amount>

The strings are found in the configuration files. plugins/MBMobEscape/classes.yml

It it does not help I need to change the behaviour of jumping in MobEscape.

**Comment by StarMonkeyHD** [comment]
This is what I did 258*1#JUMP:1 Does not work. :(

On Tue, Jun 21, 2016 at 7:41 AM, Martin Eisengardt <notifications@github.com

**Comment by mepeisen** [comment]
Please use some other item, for example 275 (Stone axe).
As I said before: The jump of iron axe is currently hard coded in MobEscape.

`275#JUMP:1*1`

**Comment by StarMonkeyHD** [comment]
Nothing happend when I leaped this time.

On Tue, Jun 21, 2016 at 5:13 PM, Martin Eisengardt <notifications@github.com

**Comment by mepeisen** [comment]
ok. You will get a code change this weekend.

**Comment by StarMonkeyHD** [comment]
Thank you

On Wed, Jun 22, 2016 at 9:38 PM, Martin Eisengardt <notifications@github.com

**Comment by StarMonkeyHD** [comment]
Tell me when it is done :3

**Comment by mepeisen** [comment]
Check out latest build.
http://nexus.xworlds.eu/nexus/content/repositories/mce-snapshots/com/github/MCE-Plugins/MGMobEscape-Plugin/1.14.9-SNAPSHOT/MGMobEscape-Plugin-1.14.9-20160701.021122-5.jar

I added an configuration option.
Edit your arenas.yml config file.

Sample for my arena (called mobescape1):

```
arenas:
  mobescape1:
    jumpFactor: 4.0
    lobby:
```

You need to add 4 spaces before "jumpFactor". This factory controls the power of your jump. Default is 1.3. A less value will make you jump Shorter, a greater value makes you jump higher/far.
