### ISSUE TITLE
Feature request: results database

### ISSUE THREAD

**Issue by SlimeDog** [MysticCity/MinigamesAPI#220]
Please consider storing individual game results in a (sqlite) database. That would allow analysis over time of player participation and statistics.

**Comment by mepeisen** [comment]
MinigamesApi already does it. I will create a wiki page the next days.

**Comment by mepeisen** [comment]
Hmmm. sqlite support is not really working.
Currently use it with mysql: https://github.com/MysticCity/MinigamesAPI/wiki/MySQL-Setup

I will rework this in the next release (1.14.16)

**Comment by mepeisen** [comment]
SQLite is now available. In config.yml you will find option "sqlite.enabled"

Latest snapshot can be found at http://www.minigameslib.de/downloads_en.php
It will be build within the next minutes.

*closed* If this does not help please respond. I will reopen the issue.

**Comment by mepeisen** [comment]
see wiki at https://github.com/MysticCity/MinigamesAPI/wiki/SQLite-Setup

**Comment by SlimeDog** [comment]
So this (for example) should be added to the config (standard YAML):
> sqlite:
  enabled: true
  database: minigames

or (as documented):
> sqlite.enabled: true
sqlite.database: minigames

**Comment by mepeisen** [comment]
nearby the config.yml :-)
You should set it to minigames.db (include file extension).

**Comment by SlimeDog** [comment]
And which version of config is correct?

**Comment by mepeisen** [comment]
it is still config version 1.

**Comment by SlimeDog** [comment]
Apologies for not being clear. Which of these is correct config:

>sqlite:
enabled: true
database: minigames


>sqlite.enabled: true
sqlite.database: minigames

**Comment by mepeisen** [comment]
First one with twi spaces before 'enabled' and 'database'.
Or simply start the Server once. It will add some defaults to your config.

**Comment by SlimeDog** [comment]
As expected. Thanks.

**Comment by SlimeDog** [comment]
> [08:21:41] [Craft Scheduler Thread - 495/INFO]: There are no files for this project

Would that message be caused by this change?

**Comment by mepeisen** [comment]
This text is not from minigames lib...
Should I reopen the issue?
What do you talk about? :-)

**Comment by SlimeDog** [comment]
The text may not be directly from MinigamesLib, but when I added the sqlite configuration, the text appeared every time a player connected. When I removed the sqlite configuration again, the text did not appear.
