### ISSUE TITLE
[Feature Request] BedWars

### ISSUE THREAD

**Issue by MCFeelBoyYT** [MysticCity/MinigamesAPI#221]
Can you add the game BedWars?

**Comment by PantallazoAzul** [comment]
https://github.com/MysticCity/BedWars ?

**Comment by mepeisen** [comment]
or https://www.spigotmc.org/threads/minigameslib.150548/
You can see the current games at https://www.spigotmc.org/resources/minigameslib.23844/
If there are any questions respond on this issue or create a new one.
