### ISSUE TITLE
How to correctly import BedWars?

### ISSUE THREAD

**Issue by PantallazoAzul** [MysticCity/MinigamesAPI#223]
**Hello!**

I'm new with all this of Maven, and I don't know how to make it works! With a clone of BedWars.

I tried different things but I got many errors (relativePath...) 👎  Can you help me please? I'm very confused. I don't know what to do when I import the Git project into my Eclipse workspace.

![screenshot](https://cloud.githubusercontent.com/assets/24450690/23566149/be1bfdd0-001e-11e7-99b8-91d265e2f253.jpg)

The screenshot is exactly the files of BedWars without modifications.

_Sorry for my bad english..._ :colombia:

**Comment by mepeisen** [comment]
The minigames are using some parent pom from MinigamesLib repository.
The simplest way is to add our nexus repository to your settings.xml

The file is normally located in your user profile:
https://maven.apache.org/settings.html#Quick_Overview

Add a repository section with "activeByDefault" set top true.
See https://maven.apache.org/settings.html#Activation and https://maven.apache.org/settings.html#Repositories for details.

Our repository url is: http://nexus.xworlds.eu/nexus/content/repositories/mce-snapshots/ for snapshots and http://nexus.xworlds.eu/nexus/content/repositories/mce-releases/ for releases.

Add it and restart eclipse. It should now find everything it needs to compile.

*closed* If this does not help please respond. I will reopen the issue.

**Comment by PantallazoAzul** [comment]
You are awesome man! I will try. Danke! :D
