### ISSUE TITLE
Option to disable the arena automatic stop timer

### ISSUE THREAD

**Issue by horgeon** [MysticCity/MinigamesAPI#224]
Hello,

I'm currently making a little mini-game using MinigamesAPI v1, which have its own map timer because of the way the mini-game is conceived (I need to start it and stop it at specific moments).

However at the moment the API does not authorize my derived Arena class to access the maximum_game_time task, so I can't cancel it myself, nor can I prevent it to start without hassles.

Can you implement a settings to disable this timer, or allow derived classes to access it ?

Regards, Horgeon

**Comment by mepeisen** [comment]
I will add an option to disable it at all (set it to -1 for unlimited or similar things).

> I need to start it and stop it at specific Moments

And I will add two methods:

restartMatchTimer and pauseMatchTimer

This should be enough to handle most situations :-)

**Comment by horgeon** [comment]
Thanks for considering this, I am looking forward to those modifications !

**Comment by mepeisen** [comment]
code for v2 (api may not yet be stable):
final ArenaInterface arena = ...
final BasicMatchTimerRuleInterface timer = arena.getRuleSet(BasicArenaRuleSets.BasicMatchTimer);
See the methods at http://git.mystic-city.de:3000/Mystic-City/MinigamesLib/src/master/v2/api/src/main/java/de/minigameslib/mgapi/api/rules/BasicMatchTimerRuleInterface.java

In v1 the methods will be available in the next version at the Arena class. Prefixed by "timer".
To pause the game you can invoke "timerPause" in v1 and "pause" in v2.

I will do the commit in the next few hours.

**Comment by mepeisen** [comment]
Latest snapshot can be found at http://www.minigameslib.de/downloads_en.php
It will be build within the next two hours.
