### ISSUE TITLE
GunGame Equip bugg and a Feature request

### ISSUE THREAD

**Issue by MCFeelBoyYT** [MysticCity/MinigamesAPI#226]
Hallo,
ich habe ein problem, wenn jemand auf meinen server joint, egal ob er schon mal drauf war oder nicht und dann von der welt Lobby auf das GunGame Schield klickt und dann in die Arena in der Welt gungame teleportiert wird ist er im spiel ganz normal, aber er hat kein equip er muss erst mit /leave leaven und dann nochmal auf das gungame Schield klicken erst dann hat er equip und kannst du vielleicht einstellen das man wenn man stirbt nur ein paar level verliert und nicht alles.

Hier ein Video wo ich es gezeigt habe:

https://www.youtube.com/watch?v=hhUfBr712qc&feature=youtu.be

World manager Plugin:

Multiverse-core

In der Welt GunGame ist die GunGame Arena und in der Welt lobby sind die Schielder um GunGame zu joinen.

Inventory Plugin:

PerWorldInventory

Config:

http://pastebin.com/wc5Hhvk1

Ich habe es auch versucht die Welten in verschiedenen gruppen zu machen, aber da kamm der gleiche bugg.

Wenn noch etwas nötig ist einfach sagen.

**Comment by mepeisen** [comment]
config: 
[wc5Hhvk1.txt](https://github.com/MysticCity/MinigamesAPI/files/822012/wc5Hhvk1.txt)

**Comment by mepeisen** [comment]
Ich habe verschiedenes ausprobiert. Leider kann ich PerWorldInventory nicht umgehen. Du müsstest es so konfigurieren, dass es das Inventar in Ruhe lässt, wenn man joint.
wir können leider nicht jedes denkbare Plugin so unterstützen, dass deren Manipulationen rückgängig gemacht werden.
