### ISSUE TITLE
Not all of the generators on BW work

### ISSUE THREAD

**Issue by Blake1Studios** [MysticCity/MinigamesAPI#227]
Only three of my Brick generators on BedWars work. Yellow works, Green works, and Blue works. Red does not. All of the generators are exactly the same and are placed in this position, but the 4th one (Red) won't spawn any Bricks. 
Position of the generator:
![image](https://cloud.githubusercontent.com/assets/13734212/24025109/64d85828-0a86-11e7-9114-369c0bb51874.png)

I have tried the following to fix this:
- Reboot the server.
- Move the generator away from the wall.
- Reload the plugins.
Nothing has worked. No idea how to replicate this either.

**Comment by PantallazoAzul** [comment]
Try using a bigger area for bounds and then /bw savearena <arena>

**Comment by mepeisen** [comment]
Correct. The blocks need to be inside the arena bounds and they will be detected once the arena is saved. If you are still having problems please comment and I will reopen the issue.

**Comment by Blake1Studios** [comment]
I see, my boundaries must have gotten messed up accidentally. Issue is fixed. Thanks for your help!
