### ISSUE TITLE
MGSnake Scoreboard Error

### ISSUE THREAD

**Issue by BBoyJD10** [MysticCity/MinigamesAPI#229]
19.03 12:51:20 [Server] WARN [MGSnake] Task #809 for MGSnake v1.14.15-20170305.080613 generated an exception
19.03 12:51:20 [Server] INFO java.lang.NoSuchMethodError: com.comze_instancelabs.mgsnake.IArenaScoreboard.get(Lorg/bukkit/scoreboard/Objective;Ljava/lang/String;)Lorg/bukkit/scoreboard/Score;
19.03 12:51:20 [Server] INFO at com.comze_instancelabs.mgsnake.IArenaScoreboard.updateScoreboard(IArenaScoreboard.java:56) ~[?:?]
19.03 12:51:20 [Server] INFO at com.comze_instancelabs.mgsnake.IArenaScoreboard.updateScoreboard(IArenaScoreboard.java:86) ~[?:?]
19.03 12:51:20 [Server] INFO at com.comze_instancelabs.minigamesapi.Arena.lambda$start$19(Arena.java:1714) ~[?:?]
19.03 12:51:20 [Server] INFO at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot.jar:git-Spigot-d4f98a3-cb61ac0]
19.03 12:51:20 [Server] INFO at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:353) [spigot.jar:git-Spigot-d4f98a3-cb61ac0]
19.03 12:51:20 [Server] INFO at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:738) [spigot.jar:git-Spigot-d4f98a3-cb61ac0]
19.03 12:51:20 [Server] INFO at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399) [spigot.jar:git-Spigot-d4f98a3-cb61ac0]
19.03 12:51:20 [Server] INFO at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:678) [spigot.jar:git-Spigot-d4f98a3-cb61ac0]
19.03 12:51:20 [Server] INFO at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:576) [spigot.jar:git-Spigot-d4f98a3-cb61ac0]
19.03 12:51:20 [Server] INFO at java.lang.Thread.run(Thread.java:745) [?:1.8.0_60]

**Comment by mepeisen** [comment]
Did you update the MinigamesLib.jar as well?

**Comment by BBoyJD10** [comment]
I will update and tell you what happens.

**Comment by mepeisen** [comment]
Download links: http://www.minigameslib.de/downloads_en.php
The complete package contains compatible jar files.

**Comment by mepeisen** [comment]
closing. If you are still having problems please comment and I will reopen the issue.
