### ISSUE TITLE
OneInTheChamber

### ISSUE THREAD

**Issue by raga70** [MysticCity/MinigamesAPI#231]
pleace help i cant join with out op vip false setenabled true no res 
clicking the sign from deoped is not working

**Comment by raga70** [comment]
m nope

**Comment by mepeisen** [comment]
I checked your issue. There is no permission you need to click on a join sign.

Can you list all plugins you are using? For example WorldGuard or similar ones may deny sign clicking.

**Comment by propotato123** [comment]
can you use command to Join game?
If yes, use cmdsign plugin

**Comment by mepeisen** [comment]
*closed* because of no response
