### ISSUE TITLE
Spam in console

### ISSUE THREAD

**Issue by MastefChief** [MysticCity/MinigamesAPI#237]
My owner just connected our minigame server to the bungee network and now it spams "[Server thread/INFO]: PlayerCount" constantly in console. Is thier a fix for this?

https://pastebin.com/AyJT6Wwc

**Comment by mepeisen** [comment]
Hmmm. First please upgrade.

> [22:39:44] [Server thread/INFO]: [MinigamesLib] Loading MinigamesLib v1.14.7

We are at V1.14.15 at the moment.
See http://www.minigameslib.de/downloads_en.php

Maybe there was some debug code in this old version. Do not know :-)

The log messages seem to log the bungee plugin messages, In V1.14.15 we are not logging them in this way and not in productive mode.
