### ISSUE TITLE
Shop & Achievements doesn´t work | GER & ENG

### ISSUE THREAD

**Issue by BCZockt** [MysticCity/MinigamesAPI#239]
Deutsch:

Bei mir funktionieren die Spiele, aber ich kann nicht den Shop in der Lobby verwenden und auch nicht das Achachievements "Item". Ich kann auch nicht über das "Leave - Item" die Lobby verlassen. Es passiert einfach nichts. Keine Errors. Brauche ich noch irgendein weiteren Plugin dafür? Kann mir jemand helfen?

Englisch:

I cannot use the shop in the lobby and the Achachievements "Item". I can also not leave over the "Leave - Item" the lobby. It simply happens nothing. No Errors. Do I still need any other Plugin for it? Can somebody help me?

**Comment by mepeisen** [comment]
Weitere Plugins werden normalerweise nicht benötigt. Passiert das nur bei einem Spiel oder bei allen?

**Comment by BCZockt** [comment]
Bei allen..

**Comment by mepeisen** [comment]
Ich habe das sowiet durchprobiert in allen Versionen.
Es klappt alles wie gewünscht.

Was für weitere Plugins hast du denn installiert? Möglicherweise werden die Features von anderen Plugins blockiert.

**Comment by mepeisen** [comment]
*closed* because of no response
