### ISSUE TITLE
Question about config: use_custom_scoreboard: false

### ISSUE THREAD

**Issue by PantallazoAzul** [MysticCity/MinigamesAPI#244]
Hello! :)
I need a little explanation about this config:
**use_custom_scoreboard: false**
For what is it? I don't find information in the wiki.

And... I need to know if is it possible to modify the scoreboard of the minigames :P (several modifications)

Thank you!

**Comment by mepeisen** [comment]
You can edit the file plugins/MGConquer/classes.yml and create your own classes with custom weapons etc.

*closed* If this does not help please respond. I will reopen the issue.

**Comment by mepeisen** [comment]
The scoreboard can currently not be edited. Only the scoreboard_title can be customized through messages.yml

If you have concret needs please report and I will reopen the issue.

**Comment by mepeisen** [comment]
Sorry, commented wrong bug ;-)

Some scoreboards can be customized, some not. Depends on the game.
If you have any needs please ask for the concret game. I will try to solve it.

**Comment by PantallazoAzul** [comment]
I need it for "BedWars", "Splegg & Spleef" and "SkyWars" :-) (and... two other custom minigames I made)
So what I have to do?

**Comment by PantallazoAzul** [comment]
Ok, know I see there's a line of "scoreboard" to edit in messages.yml, thank you :) it works fine :D

**Comment by mepeisen** [comment]
*closed* If this does not help please respond. I will reopen the issue.
