### ISSUE TITLE
Not teleported to lobby on join

### ISSUE THREAD

**Issue by Camo8315** [MysticCity/MinigamesAPI#246]
When I click join sign I don't get teleported to lobby (In splegg/spleef)

V: 1.14.15

**Comment by PantallazoAzul** [comment]
Did you set the arena correctly (/<command> savearena <arena>)? Destroy that sign and place it again.

**Comment by mepeisen** [comment]
please paste your arenas.yml

**Comment by Camo8315** [comment]
# Used for saving arena details.
mainlobby:
  world: mgm
  location:
    x: 569.5
    y: 52.0
    z: 948.5
    yaw: -0.0
    pitch: -0.0
arenas:
  Splegg:
    lobby:
      world: mgm
      location:
        x: 543.4914609035477
        y: 69.0
        z: 1304.5976262837648
        yaw: -0.7
        pitch: 0.15
  Splegg1:
    spawns:
      spawn0:
        world: mgm
        location:
          x: 106.5
          y: 57.0
          z: 964.5
          yaw: 0.0
          pitch: 0.0
      spawn1:
        world: mgm
        location:
          x: 106.5
          y: 57.0
          z: 964.5979990139604
          yaw: 0.0
          pitch: 0.0
    bounds:
      low:
        world: mgm
        location:
          x: 73.61583152295923
          y: 40.77548622744105
          z: 933.7286402387758
          yaw: 310.65002
          pitch: 11.100007
      high:
        world: mgm
        location:
          x: 135.81052031220753
          y: 70.35337413071093
          z: 991.4945360945624
          yaw: 131.70001
          pitch: 19.799984
    lobby:
      world: mgm
      location:
        x: 543.4914609035477
        y: 69.0
        z: 1304.5976262837648
        yaw: -0.7
        pitch: 0.15
    max_players: 8
    min_players: 2
    displayname: Splegg1
    is_vip: false
    sign:
      world: mgm
      loc:
        x: 547
        y: 52
        z: 949
  Splegg2:
    spawns:
      spawn0:
        world: mgm
        location:
          x: 79.62739869952202
          y: 31.0
          z: 1528.5
          yaw: -90.0
          pitch: -0.0
    bounds:
      low:
        world: mgm
        location:
          x: 105.20422905395367
          y: 11.782830428990543
          z: 1558.4079984894493
          yaw: 142.34993
          pitch: 22.49999
      high:
        world: mgm
        location:
          x: 48.5797399774071
          y: 45.58315759819508
          z: 1495.9301014163498
          yaw: -38.400085
          pitch: 29.54998
    lobby:
      world: mgm
      location:
        x: 1405.5
        y: 74.0
        z: 1363.5
        yaw: -0.6
        pitch: -0.0
    max_players: 8
    min_players: 2
    displayname: Splegg2
    is_vip: false
    sign:
      world: mgm
      loc:
        x: 547
        y: 52
        z: 947

**Comment by Camo8315** [comment]
Also is it possible to edit scoreboard on side?

**Comment by mepeisen** [comment]
For your requests on scoreboards please create a new issue and show up what exactly you need.

**Comment by mepeisen** [comment]
Sry for late answer.

Did you solve it? Everything should work. However I see problems detecting what arena is associated with a sign.
If you place multiple signs directly beside each other it may choose the wrong arena.
Does it work if you leave more that two blocks space between the join signs?

**Comment by mepeisen** [comment]
*closed* because of no response
