### ISSUE TITLE
MObEscape bug - No clue how to describe it

### ISSUE THREAD

**Issue by copvampire** [MysticCity/MinigamesAPI#247]
We seem to be having a problem with our MobEscape, we set it up correctly yet it still does not seem to work correctly. (recorded it and put it on my dropbox to show you what happens) All config files are attached in a zip.
[https://www.dropbox.com/s/h86gojo98v51bsn/2017-04-16%2020-24-12.flv](https://www.dropbox.com/s/h86gojo98v51bsn/2017-04-16%2020-24-12.flv)
[MGMobEscape.zip](https://github.com/MysticCity/MinigamesAPI/files/925399/MGMobEscape.zip)

**Comment by mepeisen** [comment]
I do not see any bug. You were eaten by the dragon. ;-)
If two players keep staying at the spawn it is random you wins. It depends on some secret magic which player is checked first.

Please respond and describe what exactly is misbehaving.

**Comment by copvampire** [comment]
If you watch the video, the dragon is way too far away from the players to "eat" them, even if the players move, they still lose the game(I could have shown that but it's hard to multiclient and move them at the same time.

**Comment by mepeisen** [comment]
Did you create enough waypoints for the dragon?
Please paste the Arenas.yml

**Comment by copvampire** [comment]
All config files for MobEscape are in the ZIP file i attached on the first post

**Comment by mepeisen** [comment]
will check it tomorrow

**Comment by mepeisen** [comment]
sry for late response.
After doing some debugging with your original arena the problem is caused by detecting if players are falling behind mob.
It seems that players are always detected for behind behind the mob. :-/

**Comment by mepeisen** [comment]
please retry by setting the first flypoint to something beyond the players spawn, for example
          x: 115.10792078292246
          y: 53.311557555660244
          z: 0.5942936836536128
          
Please respond if this helps.

**Comment by mepeisen** [comment]
fixed

Latest snapshot can be found at http://www.minigameslib.de/downloads_en.php
It will be build within the next minutes.

*closed* If this does not help please respond. I will reopen the issue.

**Comment by MizukageMaTes** [comment]
Same ploblem!
Players lose even though they are far ahead of the dragon. I'm running MinigamesLib 1.14.17 .. I already tested it with 1.14.18 and continue the month bug. I also used MobEscape 1.14.17 and 1.14.18 and it continues with the same bug! Help please!
