### ISSUE TITLE
PlayerMoveEvent Error

### ISSUE THREAD

**Issue by Muijf** [MysticCity/MinigamesAPI#249]
Hello, I installed BedWars and SkyWars and a always get this same message when you move. I've not tested any other plugins if the same happends. Here's the error:

https://pastebin.com/Vrd00jR3

**Comment by Muijf** [comment]
Oh and one other thing. When i make custom scoreboards make sure it works right cos it doesn't at the moment. You can do a max of like 3 letters per line. And make sure i can add the placeholders.

**Comment by mepeisen** [comment]
Seems that the problem is caused by wrong scoreboard initialization.
What exactly did you do? Can you paste the config?

Do you use other plugins influencing the scoreboard? Any other error in console?

I may fix the NPW but in classic spigot without additional acoreboard plugins this is nearly impossible (at least in 1.11 and 1.10).

**Comment by Muijf** [comment]
Yes iam using the AnimatedScoreboard plugin. But i've disabled the scoreboard in the lobby.
This is my MGSkyWars messages config: https://pastebin.com/W44K6yEc

And how about the PlayerMoveEvent error?

**Comment by Muijf** [comment]
Can you maybe make all placeholders for placeholderapi? so i can turn of those scoreboards and make my own. That would be awesome ^^

**Comment by mepeisen** [comment]
The exception is caused by some scoreboard issue. Seems that the other plugin overrides the scoreboard manager and returning null where bukkit never returns null. Do you have a link to the AnimatedScoreboard plugin?

**Comment by Muijf** [comment]
https://www.spigotmc.org/resources/animatedscoreboard.20848/

And iam kinda thinking about making this kind of scoreboards: http://imgur.com/TVe1yeK

**Comment by mepeisen** [comment]
Placeholder-API is already requested: https://github.com/MysticCity/MinigamesAPI/issues/192
I will check the other plugin. All I can do for 1.14.16 is to fix the NPE itself. But this will only work on Symptoms for some other bug.

**Comment by Muijf** [comment]
So are you working on placeholder api now? :)

**Comment by Muijf** [comment]
Or make it so we can use all the placeholders in the whole scoreboard? Like i can only use <arena> in the title of the scoreboard.

**Comment by mepeisen** [comment]
Latest snapshot can be found at http://www.minigameslib.de/downloads_en.php
It will be build within the next minutes.

*closed* If this does not help please respond. I will reopen the issue.

For placeholder-API watch the issue #192
