### ISSUE TITLE
Feature Request!

### ISSUE THREAD

**Issue by SmartTV20011** [MysticCity/MinigamesAPI#253]
So I was wondering if you could add a feature to disable the GUI in BedWars completly because Its interfearing with another menu I have set up so if there could be a maybe an option in the config  or something that would be great! Your plugin works amazing by the way I'm going to give it a 5 star rating thanks for making this plugin! I hope you respond shortly, thanks.

**Comment by mepeisen** [comment]
You are talking about the npc gui/ the mercants?

**Comment by mepeisen** [comment]
The option to disable the gui is found in gui.yml. "core.enabled".

Latest snapshot can be found at http://www.minigameslib.de/downloads_en.php
It will be build within the next minutes.

*closed* If this does not help please respond. I will reopen the issue.
