### ISSUE TITLE
Config and Classes problem

### ISSUE THREAD

**Issue by mrblake213** [MysticCity/MinigamesAPI#255]
I'm trying to delete the 2 classes other than default and edit something in the config.

And then I restart the server and the config and classes file keeps reverting back to default.

**Comment by PantallazoAzul** [comment]
Don't delete the internal name, just modify all but not that.

**Comment by mrblake213** [comment]
You mean I can't delete classes?

I don't want the other 2 classes, is there a way to set it to default?

**Comment by PantallazoAzul** [comment]
Try adding a line with
enabled: false

**Comment by mrblake213** [comment]
It worked for classes
but how about config

I have CratesPlus and I want to give crate keys to players when they win, this is what my config looks like:

`rewards:
    economy: false
    economy_reward: 10
    item_reward: false
    item_reward_ids: 264*1;11*1
    command_reward: true
    command: crate Key <player> Key 2
    economy_for_kills: false
    economy_reward_for_kills: 5
    command_reward_for_kills: false
    command_for_kills: pex user <player> add SKILLZ.*
    economy_for_participation: false
    economy_reward_for_participation: 5
    command_reward_for_participation: false
    command_for_participation: pex user <player> add SKILLZ.*`

**Comment by mepeisen** [comment]
This should not happen. Did you edit the file while the server is online or offline?

**Comment by mrblake213** [comment]
Thanks.
It's fixed now.

**Comment by mepeisen** [comment]
thx for Response.
Closing this issue now.
