### ISSUE TITLE
Basic questions

### ISSUE THREAD

**Issue by WyRe** [MysticCity/MinigamesAPI#256]
Do you haven't got IRC channel on irc.spi.gt? 

What would be the MG plugin more like hunger games?

**Comment by mepeisen** [comment]
No IRC, sry.

Currently there is no plugin like Hunger Games. But it is planned.

We have several more simple PvP games: OneInTheChamber, SkyWars...

**Comment by mepeisen** [comment]
*closed* If this does not help please respond. I will reopen the issue.
