### ISSUE TITLE
PlayerCount console spam

### ISSUE THREAD

**Issue by CallmePyrus** [MysticCity/MinigamesAPI#258]
To start off, I'm not sure whether this is a problem with MGApi or if it's a problem with the MGConquer plugin itself, but, we're constantly getting spammed with PlayerCount in the console after adding both plugins to the server.

The "Error" / problem looks like this.

https://gyazo.com/861e4b7dbe5593793cb2b6b0234397da?token=7cf13b3ed61ab1b85d72f28d31351a3c

Anybody else encountered this, if it's a thing of the past, how did you fix it?

EDIT:

Found this 2 seconds later.
https://www.spigotmc.org/threads/bungee-cord-console-spam.68551/

Problem is certainly from here, any fix?

**Comment by mepeisen** [comment]
Which version do you use? The current version does not do any logInfo with ths text.

**Comment by mepeisen** [comment]
*closed* because of no response
