### ISSUE TITLE
Spigot 1.12 support

### ISSUE THREAD

**Issue by SlimeDog** [MysticCity/MinigamesAPI#263]
Public Spigot 1.12 release is imminent. There are a myriad of errors reported on start-up and beyond, for MinigamesLib/MG* 1.14.16-20170514.144611.

**Comment by mepeisen** [comment]
1.12 is pre and md_5 says API may still change.
As soon as 1.12 is released MinigamesLib will be migrated :-)

**Comment by mepeisen** [comment]
1.12 was released. I will add support this weekend.

**Comment by mepeisen** [comment]
Latest snapshot can be found at http://www.minigameslib.de/downloads_en.php
It will be build within the next minutes.

*closed* If this does not help please respond. I will reopen the issue.
