### ISSUE TITLE
Conquer Issue

### ISSUE THREAD

**Issue by LeeRy30** [MysticCity/MinigamesAPI#268]
Hello,
I LOVE the Conquer gamemode and would love to be able to keep it however, the majority of games that get played, there is an issue for generally one team but sometimes both. The checkpoints start changing colour and then it will randomly skip a block (It stays white) which will prevent them from claiming the checkpoint. Then if the other team tries to claim the checkpoint, it normally works for them. It happens during most games and even after the other team claim it, the team with the issue still has the same problem when they try again. I have tried setting up the arena again and again but nothing worked... Any help would be greatly appreciated!
Hope you're having a great day!
Thanks!

**Comment by mepeisen** [comment]
Which version are you using?

**Comment by LeeRy30** [comment]
1.10 thanks for the reply!!

**Comment by LeeRy30** [comment]
If you mean which version of Conquer... The latest!

**Comment by LeeRy30** [comment]
Tried 1.14.18 and the error still occured however, I think this may be the console error from it:
13.06 19:40:44 [Server] WARN [MGConquer] Task #129321 for MGConquer v1.14.17-20170612.054138 generated an exception
13.06 19:40:44 [Server] INFO java.lang.NullPointerException
13.06 19:40:44 [Server] INFO at com.comze_instancelabs.conquer.CheckPoint.evaluate(CheckPoint.java:39) ~[?:?]
13.06 19:40:44 [Server] INFO at com.comze_instancelabs.conquer.IArena$2.run(IArena.java:225) ~[?:?]
13.06 19:40:44 [Server] INFO at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[Spigot110.jar:git-Spigot-c3e4052-1953f52]
13.06 19:40:44 [Server] INFO at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [Spigot110.jar:git-Spigot-c3e4052-1953f52]
13.06 19:40:44 [Server] INFO at net.minecraft.server.v1_10_R1.MinecraftServer.D(MinecraftServer.java:741) [Spigot110.jar:git-Spigot-c3e4052-1953f52]
13.06 19:40:44 [Server] INFO at net.minecraft.server.v1_10_R1.DedicatedServer.D(DedicatedServer.java:399) [Spigot110.jar:git-Spigot-c3e4052-1953f52]
13.06 19:40:44 [Server] INFO at net.minecraft.server.v1_10_R1.MinecraftServer.C(MinecraftServer.java:672) [Spigot110.jar:git-Spigot-c3e4052-1953f52]
13.06 19:40:44 [Server] INFO at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:571) [Spigot110.jar:git-Spigot-c3e4052-1953f52]

**Comment by mepeisen** [comment]
Seems to happen if spectators are involved. However I fixed it. Hope that it is robust enough now.

Latest snapshot can be found at http://www.minigameslib.de/downloads_en.php
It will be build within the next minutes.

*closed* If this does not help please respond. I will reopen the issue.
