### ISSUE TITLE
Version number internal <> external

### ISSUE THREAD

**Issue by SlimeDog** [MysticCity/MinigamesAPI#27]
Examples:

MinigamesLib-1.14.9-SNAPSHOT.jar when loaded displays:
>version MinigamesLib
[15:54:32 INFO]: MinigamesLib version 1.14.8

https://www.spigotmc.org/resources/snake.23906/ displays:
Snake 1.3.5
but:
>version MGSnake
[15:56:46 INFO]: MGSnake version 1.3.3

I (and others) use this information to automate version update notification. Please keep version numbers in sync. Very much appreciated.

**Comment by SlimeDog** [comment]
Please include the build numbers in the internal version numbers. Example from build 22:

MinigamesLib-1.14.9-SNAPSHOT ---> MinigamesLib-1.14.9-10 or MinigamesLib-1.14.9-SNAPSHOT-10
MGFlyingCars-1.14.9-SNAPSHOT ---> MGFlyingCars-1.14.9-8 or MGFlyingCars-1.14.9-SNAPSHOT-8
MGSnake-1.14.9-SNAPSHOT ---> MGSnake-1.14.9-8 or MGSnake-1.14.9-SNAPSHOT-8

Thanks in advance.

**Comment by mepeisen** [comment]
SNAPSHOT versions in maven have a special logic. But it is possible to write some other string into plugin.yml to fit your needs.

What I will do here with next commit is to use the maven timestamp. This will generate the suggested version in plugin.yml but without build number.
For example: "1.14.9-20160621.061236"
As the timestamp increments you can detect if there are newer versions around.

To divide snapshots from final build versions may contain a suffix "final"?
So the we get version numbers "1.14.9-20160621.061236" and "1.14.9-20160622.050505" for unstable snapshots and a "1.14.9-20160625.010101-final" for the release? This is OK?

Note: The timestamp for uploading the minigames-all archive won't be the same than used in the plugin.yml.
Simple example:
Bedwars build 8 is called: BedWars-Plugin-1.14.9-20160621.061913-8.jar
But is is packaged within Minigames-All-1.14.9-20160621.062025-22-bin.zip

Detecting newer versions should always be done on game level, not on minigames-all package.

And please watch issue #23. I already planned a review of updating progress. This may result in some smarter command or something similar. For example a small web site that can be queried to fetch the newest version number from nexus etc. This can nicely be integrated in your self-written external administration software you use to detect newer versions :-)

**Comment by SlimeDog** [comment]
Thanks. The timestamps are not as useful (to me) as the build numbers, but sufficient, I guess. I appreciate (and noted implicitly in my comment) that different games have different build numbers. I have no issue with that.
