### ISSUE TITLE
Add some "needed" placeholders

### ISSUE THREAD

**Issue by altrisi** [MysticCity/MinigamesAPI#275]
For example, in the kit selection add a placeholder like {is_selected}. If it's true, change it for a message in the messages file (something like "&aSELECTED"), and if it is false, something like "&eCLICK TO SELECT".
Also in shop something like {is_purchased}. If it's true, change it for a message in the message file like "&cALREADY PURCHASED" and if it's false something like "&eCLICK TO PURCHASE".

**Comment by mepeisen** [comment]
Will be solved in 2.0.0. We will not support those "dynamic" strings directly.

But: You can use the PlaceholderAPI to solve this with enabled JavaScript feature.
There is already a plugin connecting the new core library (mclib) to PlaceholderAPI:
https://github.com/mepeisen/mclib/tree/master/modules/impl/mclib-thirdparty
See JavaScript samples from spigot resource page:
https://www.spigotmc.org/resources/placeholderapi.6245/

I will move it to 2.0 for adding the requires placeholders.

**Comment by altrisi** [comment]
Closing as stale.
