### ISSUE TITLE
UUID not used for everithing

### ISSUE THREAD

**Issue by altrisi** [MysticCity/MinigamesAPI#276]
Currently, in Achievements, Classes and left_players are saving data with playername instead of UUID.
Only seen UUID working in stats.
This applies to (almost, not all tested) all minigames.

**Comment by mepeisen** [comment]
No more feature requests for 1.x

And yes, for 2.0 we force usage of UUIDs for every player reference. No more user name reference.

**Comment by mepeisen** [comment]
already solved in 2.0

**Comment by altrisi** [comment]
This isn't a feature request. In an update/feature I can't remember what it was, it was saying that "the plugin now uses UUID for player data", not "for player stats", so this isn't a feature request, this is a Bug API/Lib.

**Comment by mepeisen** [comment]
It is ok to think of it as a bug that is solved in version 2.0

Since the first playable version of 2.0 OITC will arrive soon I don't think I will spent a huge time for refactoring to the old versions.
