### ISSUE TITLE
MGSeaBattle: Player Glitching

### ISSUE THREAD

**Issue by RedBorne007** [MysticCity/MinigamesAPI#277]
Can someone help me with this problem? My problem is.. When I tried to start and play the arena. It glitching [Every player out of boat and player started to glitching and then everyone lost the game]. Is this some kind of bug or else? :( [I'm using 1.8 Server, Lastest MGSeaBattle version + MGLib version]. Here is some screenshots.
![2560-06-20_20 34 18](https://user-images.githubusercontent.com/29576098/27337694-5b4a1c20-55fd-11e7-93fc-763482ce5328.png)

And my arena.yml

# Used for saving arena details.
mainlobby:
  world: world
  location:
    x: 170.5851885098968
    y: 72.0
    z: 147.30000001192093
    yaw: -358.1996
    pitch: 2.0999594
arenas:
  sealife:
    lobby:
      world: world
      location:
        x: 171.07783410605674
        y: 75.0
        z: 162.03985806439493
        yaw: -273.4494
        pitch: 17.099974
    spawns:
      spawn0:
        world: world
        location:
          x: 168.46058220195036
          y: 75.0
          z: 163.53180477660402
          yaw: -75.599495
          pitch: 90.0
      spawn1:
        world: world
        location:
          x: 174.44976248391632
          y: 75.0
          z: 158.50732325916016
          yaw: -86.84948
          pitch: 90.0
      spawn2:
        world: world
        location:
          x: 178.47935987637612
          y: 75.0
          z: 165.53483359291263
          yaw: -79.949486
          pitch: 90.0
      spawn3:
        world: world
        location:
          x: 173.5122185772156
          y: 75.0
          z: 169.4767340027196
          yaw: 6.4505215
          pitch: 90.0
    max_players: 4
    min_players: 2
    displayname: sealife
    is_vip: false
    sign:
      world: world
      loc:
        x: 170
        y: 73
        z: 153

**Comment by mepeisen** [comment]
try to set arena bounds. They must be one or two blocks below your water surface and one or two blocks above the spawns.

**Comment by RedBorne007** [comment]
What is the low and high bounds? (in /[cmd] setbounds [low/high])

**Comment by mepeisen** [comment]
lower bounds is an edge with less y coordinate (below water surface) and upper bound an edge with greater y coordinate (above water surface).

**Comment by RedBorne007** [comment]
Am I doing right?
![2560-06-20_22 26 01](https://user-images.githubusercontent.com/29576098/27341483-9499a338-5607-11e7-9395-4fd5d8d2f994.png)

**Comment by RedBorne007** [comment]
I'm trying to set low bounds under water surface and high bounds above water surface. But It still glitching. Should I downgrade version of plugin?

**Comment by mepeisen** [comment]
no. Please send me details about your server at mep_eisen@web.de
I will try to watch what is happening

**Comment by RedBorne007** [comment]
Here is what it's happening
![source](https://user-images.githubusercontent.com/29576098/27342675-02044952-560b-11e7-9172-7d00b0c14d42.gif)

**Comment by mepeisen** [comment]
Can you send meyour server address?
 

Gesendet: Dienstag, 20. Juni 2017 um 17:51 Uhr
Von: RedBorne007 <notifications@github.com>
An: MysticCity/MinigamesAPI <MinigamesAPI@noreply.github.com>
Cc: "Martin Eisengardt" <mep_eisen@web.de>, Comment <comment@noreply.github.com>
Betreff: Re: [MysticCity/MinigamesAPI] MGSeaBattle: Player Glitching (#277)


Here is what it's happening

**Comment by RedBorne007** [comment]
You mean my Server IP Address?

**Comment by mepeisen** [comment]
Yes. Please send it to my email address. No Need to publish it on github ;-)

**Comment by RedBorne007** [comment]
Err... Sorry... I'm using on Testing server which is on my computer [Not using any Online Hosting Server].

**Comment by mepeisen** [comment]
hmmm. ok. Then please wait till Weekend. I will try to reproduce it with arenas.yml you quoted above.

**Comment by RedBorne007** [comment]
OK Thanks for you help anyway! :) I will try to downgrade the version and testing it soon to check other bugs.
