### ISSUE TITLE
Splegg ignoring permissions - wiki edit

### ISSUE THREAD

**Issue by pogof** [MysticCity/MinigamesAPI#278]
Hi,
I was just about to submit an issue about Splegg ignoring permissions. But when I coppied the classes.yml config here I just found the culprit! There is settings to enable permissions for every class. It was two day hunt where is the problem. Could you please edit permissions wiki page with something that you need to enable that first? It was one of the primary sources for solvint this issue and it would be helpful to have this line somewhere there. Thank you. Anyway great plugin working like a charm!

**Comment by mepeisen** [comment]
changed wiki a bit. Thanks for this issue. :-)
