### ISSUE TITLE
Bedwars - complete wiki with information about arena bounds

### ISSUE THREAD

**Issue by TheUser816** [MysticCity/MinigamesAPI#279]
Server Version: **1.8.8**
Plugin Version: **tested with 1.14.17 and 1.14.18**
What: **Itemspawners are not working at all** // Item Spawner funktionierten nicht
When: 25.06.2017 ~22:00 Uhr
Any errors in console: **no errors in console**

Thank you! If you need help in fixing the bug, just message me.

### Solution: Set the arena bounds with ’/bw setbounds [Arena] [low/high]’

**Comment by mepeisen** [comment]
Did you set the arena bounds? 
Did you save the arena after setting the blocks?

**Comment by TheUser816** [comment]
Nothing like "bounds" were mentioned in the setup guide on [SpigotMC - MGBedwars](https://www.spigotmc.org/resources/bedwars.27903/) and in the command section on [Github -
 MGBedwars wiki](https://github.com/MysticCity/MinigamesAPI/wiki/MGBedWars).

Please complete it for others, who have the same issue with the spawners like me. (F.e. look into your reviews, at least two more people had issues with spawners too)

**Comment by mepeisen** [comment]
updated
