### ISSUE TITLE
Leave signs ignore formatting

### ISSUE THREAD

**Issue by SlimeDog** [MysticCity/MinigamesAPI#28]
Config in messages.yml:  _leave: ... '1': '&4&lLeave'_
did not display bold, after neither **/snake reload** nor server reboot.

**Comment by mepeisen** [comment]
Please retry.
I checked this issue with latest build and a sample snake Arena. It works 8see screenshot).
My messgaes.yml contains: 'LEAVE&4&lLeave'

![2016-07-01_04 19 44](https://cloud.githubusercontent.com/assets/454402/16510069/4a5f8b60-3f43-11e6-8c63-a8916d425d3e.png)

**Comment by mepeisen** [comment]
will close it for now. If the issue still exists please comment.
