### ISSUE TITLE
Feature request - Achievements, messages file

### ISSUE THREAD

**Issue by TheUser816** [MysticCity/MinigamesAPI#280]
Achievements menu in gamemodes -> **Lore of archievement items**
Translatable and **custom text for "Done: true"** in config or messages / language file.

Thank you very much! I would really like to see this in the next update, as a normal user woun’t be able to change this in the sourcecode.

**Comment by mepeisen** [comment]
fixed. see messages.yml after restart.

Latest snapshot can be found at http://www.minigameslib.de/downloads_en.php
It will be build within the next minutes.

*closed* If this does not help please respond. I will reopen the issue.
