### ISSUE TITLE
Party invite is case-insensitive, other actions are

### ISSUE THREAD

**Issue by horgeon** [MysticCity/MinigamesAPI#282]
Using MinigamesAPI v1 compiled as of ae27f78, party actions are case-sensitive except invitation.

It causes issues where players seems to be invited but can not join.

It is likely caused by Bukkit.getPlayer which is case-insensitive.

One solution may be to get the target player in partyInvite method from [CommandHandler.java](https://github.com/MysticCity/MinigamesAPI/blob/ae27f78fbe4a0bb6cee6494e4b62e60355989f66/API/src/main/java/com/comze_instancelabs/minigamesapi/commands/CommandHandler.java#L1430) after the validation and uses his name directly (getName()) instead of the first command argument, so it uses the exact player name.

I hope you will consider fixing this.

**Comment by mepeisen** [comment]
Fixed by complete refactoring. Party system uses UUIDs now.

Latest snapshot can be found at http://www.minigameslib.de/downloads_en.php
It will be build within the next minutes.

*closed* If this does not help please respond. I will reopen the issue.
