### ISSUE TITLE
Feature Requast: MGBedWars Coloered Beds For 1.12

### ISSUE THREAD

**Issue by bluefutureMC** [MysticCity/MinigamesAPI#284]
1.12 added new colored beds in to the game, I think it would be cool if you could make it that in 1.12 each team has its own colored bed depending by its team color.

If not, then please add a configuration for bed block in the config

**Comment by mepeisen** [comment]
solved

Latest snapshot can be found at http://www.minigameslib.de/downloads_en.php
It will be build within the next minutes.

*closed* If this does not help please respond. I will reopen the issue.
