### ISSUE TITLE
Item spawn

### ISSUE THREAD

**Issue by lightda104530** [MysticCity/MinigamesAPI#289]
Item Spawn??

**Comment by mepeisen** [comment]
Some more details?
Are you talking about bedwars?

**Comment by rh-programm** [comment]
In Bedwars often spawn no items - gold / silver / bronze

please fix it

Sorry for my bad English

**Comment by mepeisen** [comment]
You created the blocks?
- hardened clay http://minecraft.gamepedia.com/Hardened_Clay
- iron block http://minecraft.gamepedia.com/Block_of_Iron
- Gold block http://minecraft.gamepedia.com/Block_of_Gold

After creating the blocks you need to save the arena. Currently the blocks are only detected while saving.

**Comment by mepeisen** [comment]
And the blocks need to be inside the arena bounds.

**Comment by rh-programm** [comment]
Yes, I created the blocks and they are inside the arena.

**Comment by mepeisen** [comment]
Can I watch this online? please send me your server data to mep_eisen@web.de

**Comment by mepeisen** [comment]
*closed* If this does not help please respond. I will reopen the issue.
