### ISSUE TITLE
MobEscape: Dragon Destruction Blacklist

### ISSUE THREAD

**Issue by YouGamePlayHD** [MysticCity/MinigamesAPI#291]
Hey,
could you add a blacklist for the dragon? Any block not listed on said list will be destroyed, but the blocks (or liquids!!) listed won't be destroyed. It's a good idea for e.g. ocean or lava maps.
Thanks in advance

EDIT: Actually the dragon creates LOTS of lag when it destroys water in particular!

**Comment by mepeisen** [comment]
Within config.yml there are two new values:
config.liquid_particles (boolean flag)
and
config.block_blacklist (string value)

See wiki at https://github.com/MysticCity/MinigamesAPI/wiki/MGMobEscape for details.

Latest snapshot can be found at http://www.minigameslib.de/downloads_en.php
It will be build within the next minutes.

*closed* If this does not help please respond. I will reopen the issue.
