### ISSUE TITLE
Plugin don't read config.yml

### ISSUE THREAD

**Issue by Ninja71172** [MysticCity/MinigamesAPI#316]
Changes text in config.yml do not matter. For example i set:
  defaults:
    default_max_players: 20
    default_min_players: 8
But nothing happen. Still 8 players is maximum like in orginal not configured config.yml. Sorry for my ENG. I love this plugin 🥇

**Comment by Ninja71172** [comment]
MC 1.12.1
Spigot 1.12.1-R0.1
latest MinigamesLIB
latest Conquer

**Comment by mepeisen** [comment]
The min/max players in config.yml only affect for NEW arenas.
You still have to set the value for each single arena (arenas.yml or via command).

*closed* If this does not help please respond. I will reopen the issue.
