### ISSUE TITLE
MinigamesLib - Mutable minigames? 

### ISSUE THREAD

**Issue by OkiePlays** [MysticCity/MinigamesAPI#320]
so i had skywars installed on my server, and now I try to install bedwars and get this command when /bw 
![2017-09-09_22 35 19](https://user-images.githubusercontent.com/31812551/30245930-45edbb74-95af-11e7-8e03-82353b02a779.png) but skywars works just fine, i tryed adding other games aswell but i get the same thing just for the games after skywars was added 
![2017-09-09_22 36 50](https://user-images.githubusercontent.com/31812551/30245933-6457cbae-95af-11e7-842f-c96d8bf9f467.png)

**Comment by mepeisen** [comment]
Are there any errors in console? There may be an exception.
Which versions did you install? Which spigot do you use?

**Comment by OkiePlays** [comment]
i have all the newer versions of the minigames and spiggot 1.12, dont know the rest tho, yeah there is alot of errors in the consol - [14:05:27 ERROR]: Could not pass event CreatureSpawnEvent to MGBedWars v1.14.16-20170514.145344org.bukkit.event.EventException: null        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot.jar:git-Spigot-596221b-9a1fc1e]        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot.jar:git-Spigot-596221b-9a1fc1e]        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:499) [spigot.jar:git-Spigot-596221b-9a1fc1e]        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:484) [spigot.jar:git-Spigot-596221b-9a1fc1e]        at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.callCreatureSpawnEvent(CraftEventFactory.java:283) [spigot.jar:git-Spigot-596221b-9a1fc1e]        at net.minecraft.server.v1_12_R1.World.addEntity(World.java:1041) [spigot.jar:git-Spigot-596221b-9a1fc1e]        at net.minecraft.server.v1_12_R1.WorldServer.addEntity(WorldServer.java:1112) [spigot.jar:git-Spigot-596221b-9a1fc1e]        at net.minecraft.server.v1_12_R1.SpawnerCreature.a(SpawnerCreature.java:188) [spigot.jar:git-Spigot-596221b-9a1fc1e]        at net.minecraft.server.v1_12_R1.WorldServer.doTick(WorldServer.java:286) [spigot.jar:git-Spigot-596221b-9a1fc1e]        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:798) [spigot.jar:git-Spigot-596221b-9a1fc1e]        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:405) [spigot.jar:git-Spigot-596221b-9a1fc1e]        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:678) [spigot.jar:git-Spigot-596221b-9a1fc1e]        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:576) [spigot.jar:git-Spigot-596221b-9a1fc1e]        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]Caused by: java.lang.NoSuchMethodError: com.comze_instancelabs.minigamesapi.ArenaListener.onMobSpawn(Lorg/bukkit/event/entity/

**Comment by mepeisen** [comment]
You are using incompatible versions.
MinigamesLib and the minigames should have the same version numbers.
You can download the complete package with compatible versions at http://www.minigameslib.de/downloads_en.php
*closed* If this does not help please respond. I will reopen the issue.

**Comment by OkiePlays** [comment]
oh thanks

**Comment by OkiePlays** [comment]
now how would i check what version i am using?

**Comment by mepeisen** [comment]
The versions are printen in console log. Right after starting the Server.
