### ISSUE TITLE
Skywars kits bug 

### ISSUE THREAD

**Issue by OkiePlays** [MysticCity/MinigamesAPI#324]
so im making alot of kits for my skywars minigame for my school and it will only let me use the top row, how do i fix this

**Comment by mepeisen** [comment]
Did you really set the spawns for the correct arena?
Or did you set them for the first one?

**Comment by OkiePlays** [comment]
so i tried to add more kits than this but it keeps resting to the older version sence i added more kits than the row used 
![2017-09-12_17 41 37](https://user-images.githubusercontent.com/31812551/30351591-d38fcc04-97e1-11e7-839c-f9085cf73497.png) so i tryed to add kits to the secound row but idk how

**Comment by mepeisen** [comment]
My previous comment went wrong. Schould be in another bug.

Thx for screenshot. 
Your problems seem to be a real bug. Will be fixed soon.

**Comment by OkiePlays** [comment]
thankyou

**Comment by mepeisen** [comment]
Trying to fix it I found a hidden option in config.yml.
GUI.classes_gui_rows
Maybe it is set to 1? Try to increase the value. I testet it and it uses more than one row.

*closed* If this does not help please respond and send me your classs.yml. I will reopen the issue.
