### ISSUE TITLE
MGSplegg Spec Bounds problem.

### ISSUE THREAD

**Issue by Strikenz** [MysticCity/MinigamesAPI#351]
I seem to be having trouble setting up the spec bounds, no matter where I put it, it will always default back to the default area (Being up high in a single y-axis) I ended up moving the bounds of the arena in-case they interfered with each other but was still pushed up to the default one (Tried using setspecspawn, although if you move a single block you're pushed back up again)

Hopefully I'm doing something wrong, but as for now I'm unsure what it would be, Thanks!

**Comment by ConnorFranta** [comment]
Hi @Strikenz.
You seem to have one of the same issues that I also had.
Go into Plugins -> MGSplegg -> config.yml
Go to line 18 or look for "spectator:" in the third section. You will see "spectator_move_y_lock: true" set this to false, save, then '/sp reload' in-game. (you may have to reboot if it still does it, simple reload should work)
This setting is so they will spawn X amount of blocks above the arena, setting it to false makes it use the "/sp setspecspawn [arena]" location instead.

Hope this helps!

**Comment by Strikenz** [comment]
Aha, so it was a simple fix, Thank you so much!
