### ISSUE TITLE
Seabattle: Hitting Yourself With Snowballs

### ISSUE THREAD

**Issue by Yellowdash34** [MysticCity/MinigamesAPI#39]
Before I report this issue. I want to give some context about how my arena works.

I spawn players on land 1 block away from water. They then paddle their boats into the water. The reason I do this is because if I spawn them in or above water they sink into it.

I'm in my boat ready to throw a snowball, but every time I throw the snowball it hits me, not the thing I  was throwing it at.

**Comment by mepeisen** [comment]
I cannot reproduce it. Even if I look down and throw at my own boat it does not count a hit.
Can you give some details? Spigot version? Any additional plugins? What version of Minigames-Lib and SeaBattle are you using?

**Comment by Yellowdash34** [comment]
Plugin List: HiveJumpPads, WorldEdit, ChestEx, ClearLag, ChatControl, Votifier, Multiverse-Core, WorldGuard, AdvancedPortals, ArrowEffect, PermissionsEx, ViaVersion, GAListener, Vault, Essentials, ProtocolLib, LibsDisguises, ServerSigns, EnjinMinecraftPlugin, UltraCosmetics, HolographicDisplays, MinigamesLib, MGSkyWars, MGOITC, MGDeathRun, MGMobEscape, MGFlyingCars, MGSnake, MGGungame, MGSeaBattle, MGArcade

Versions:
MinigamesLib v1.14.8
MGSeaBattle v1.1.3
Server Version is Spigot for 1.9.4

**Comment by mepeisen** [comment]
can you please re-test with latest snapshot?

http://nexus.xworlds.eu/nexus/content/repositories/mce-snapshots/com/github/MCE-Plugins/Minigames-All/1.14.9-SNAPSHOT/Minigames-All-1.14.9-20160702.102744-36-bin.zip

(copy the minigames you need and delete the rest except minigames-api).
If the bug still exists there may be an influence of some other plugin. Can you deactivate them step by step?
I tested it with: esentialsX, vault and Crackshot.
No frther plugins.

**Comment by Yellowdash34** [comment]
I think it's fixed. Thanks!
