### ISSUE TITLE
Blank Minigames

### ISSUE THREAD

**Issue by NocturneCZ** [MysticCity/MinigamesAPI#40]
My request for a feature is simple. To be able to make "blank" minigames. You would only have a lobby premade and then you could make minigame for example via command blocks. I want to make a command block based minigames on my server, but the lobbys are with command blocks just too complicated. As you can see:

![2016-06-30_20 34 03](https://cloud.githubusercontent.com/assets/17685682/16499820/458553d6-3f02-11e6-9a0f-a47b44ee5a98.png)

![2016-06-30_20 34 20](https://cloud.githubusercontent.com/assets/17685682/16499825/4d91336a-3f02-11e6-8b18-0ce579f4e18c.png)

If you could make that you would only have a lobby and than you could make game mechanics yourself, that would be great

**Comment by MysticCity** [comment]
LoL you create Minigames with CB and cant create an Lobby ^^

Sorry but an Empty Minigame is.... 
No Thanks ^^
