### ISSUE TITLE
MingamesLib and SkyWars leave errors

### ISSUE THREAD

**Issue by Goldentoenail** [MysticCity/MinigamesAPI#41]
Although I have not played this myself, I get reports of players who can't leave the minigame.
On one occasion I checked the commands and permissions which seem to be fine. And had to teleport the player out of the game. Most of the time the player just quits the server.

This has happened both before and after trying to use the 1.10 snapshots from http://nexus.xworlds.eu/nexus/servi...nigames-All-1.14.9-20160619.021615-13-bin.zip

Here is the console log http://pastebin.com/e0gCjv1a for the 1.10 snapshots

**Comment by mepeisen** [comment]
NPE fixed. Please retry with latest snapshot if the NPE caused the problems.
http://nexus.xworlds.eu/nexus/content/repositories/mce-snapshots/com/github/MCE-Plugins/Minigames-All/1.14.9-SNAPSHOT/Minigames-All-1.14.9-20160702.102744-36-bin.zip

**Comment by Goldentoenail** [comment]
I'll give it a try, thank you.

**Comment by Goldentoenail** [comment]
I am still having the same problem using the suggested snapshot
