### ISSUE TITLE
MGsnake coutdown problem

### ISSUE THREAD

**Issue by bluefutureMC** [MysticCity/MinigamesAPI#52]
When a game start the timer is counting and then it starts to count negative and the game doesn't start!!!

**Comment by mepeisen** [comment]
Which Version are you using?
Are there any exception in the console?

**Comment by bluefutureMC** [comment]
I'm using spigot 1.10 and when the game start the console is full of errors.

**Comment by mepeisen** [comment]
Which minigames version are you using?

**Comment by bluefutureMC** [comment]
It has auto update then I guess that the latest.

**Comment by mepeisen** [comment]
The auto update feature is not working for development builds.
The upcoming 1.14.9 is the only version working with spigot 1.10.
Please retry with the following snapshot: http://nexus.xworlds.eu/nexus/content/groups/mce/com/github/MCE-Plugins/Minigames-All/1.14.9-SNAPSHOT/

**Comment by bluefutureMC** [comment]
Oo.. Thx

**Comment by mepeisen** [comment]
Did the snapshot solve your problem?
I will close the issue.
Feel free to re-open/ comment if there are further errors and exceptions.

**Comment by bluefutureMC** [comment]
Yes it works now thx for the support
