### ISSUE TITLE
Trade bugs

### ISSUE THREAD

**Issue by mepeisen** [MysticCity/MinigamesAPI#66]
- Disable the "give experience" on trades
- Sometimes players are blocked from trading even if two different teams are trading (one teams blocks the other)

**Comment by YouGamePlayHD** [comment]
Uhmmm, where do u download BedWars xD?

**Comment by mepeisen** [comment]
http://nexus.xworlds.eu/nexus/content/groups/mce/com/github/MCE-Plugins/MGBedWars-Plugin/1.14.9-SNAPSHOT/
Or
http://nexus.xworlds.eu/nexus/content/groups/mce/com/github/MCE-Plugins/Minigames-All/1.14.9-SNAPSHOT/
