### ISSUE TITLE
Compatibility with 1.9.4

### ISSUE THREAD

**Issue by relampagorojo93** [MysticCity/MinigamesAPI#96]
Hi,
Well, today I updated my server to 1.9.4, because in one message, it says  that minigamesLib was compatible with 1.9.4. So, I tried, and minigamesLib doesn't work. Why?

**Comment by mepeisen** [comment]
Which version of minigames lib do you use?
Which game and which game version? 

Any errors in console?

**Comment by relampagorojo93** [comment]
I'm using minigames lib 1.14.10, the problem isn't the game, is the trying to load of the server, the error is this:

[08:51:56] [Server thread/ERROR]: Could not load 'plugins\MinigamesLib-1.14.10.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: java.lang.UnsupportedClassVersionError: com/comze_instancelabs/minigamesapi/MinigamesAPI : Unsupported major.minor version 52.0

**Comment by mepeisen** [comment]
Please upgrade java to 1.8

**Comment by relampagorojo93** [comment]
Fucking shit, I forgot that this error was for java versions XD, well, my server is going to get destroyed with java 8 :B

**Comment by mepeisen** [comment]
That was a joke?  😀

**Comment by relampagorojo93** [comment]
Something similar XD I had a lot of problems with java 8, for that I only used 7

**Comment by mepeisen** [comment]
Problems related to minecraft? Maybe i can give you a 1.7 build but this will only work for the 1.14 releases. The upcoming version 2 of minigames lib uses lots of java 1.8 Features.

**Comment by mepeisen** [comment]
Another option is to use java 8 for minecraft only.

**Comment by relampagorojo93** [comment]
Nah, no problem, I updated to java 8, for the moment it works fine, I need to check if I can update other plugins to don't have problems

**Comment by mepeisen** [comment]
ok. I will close this issue now.
