### ISSUE TITLE
SkyWars Lobby Bug

### ISSUE THREAD

**Issue by masterhacka** [MysticCity/MinigamesAPI#97]
Hi there,

I'm having c chunk bug when joining the lobby or when I'm leaving the game and join the mainlobby. But mostly the problem appears while leaving the game and coming back to the main lobby. You can see through the map.

Mainlobby (normally):
![2016-08-16_11 21 52](https://cloud.githubusercontent.com/assets/9753608/17694369/ccb0b3ee-63a3-11e6-956d-4ab95a813e69.png)
![2016-08-16_11 21 57](https://cloud.githubusercontent.com/assets/9753608/17694368/cca43998-63a3-11e6-87b2-b273a8df93a7.png)

Mainlobby(bug):
![2016-08-16_11 19 12](https://cloud.githubusercontent.com/assets/9753608/17694367/cc9e7eb8-63a3-11e6-806a-cdf6c5f57fac.png)
![2016-08-16_11 19 25](https://cloud.githubusercontent.com/assets/9753608/17694366/cc9d2310-63a3-11e6-9b9c-e8052924be2e.png)

Arena lobby:
![2016-08-16_11 26 02](https://cloud.githubusercontent.com/assets/9753608/17694487/5adaef7c-63a4-11e6-8d8a-d50339a38897.png)
![2016-08-16_11 26 05](https://cloud.githubusercontent.com/assets/9753608/17694488/5adb3c3e-63a4-11e6-9afc-d7efe49d1e5f.png)

Also there is a bug that the items are duplicating, if you have items in the world where the mainlobby is.

**Comment by mepeisen** [comment]
Which spigot version? Which minigame version?

> Also there is a bug that the items are duplicating, if you have items in the world where the mainlobby is.

Gane you give a clear example? What excactly are you doing? When does it happen? Playing normally? Leaving by chat command? Did you leave the game or the waiting lobby?

**Comment by masterhacka** [comment]
> Which spigot version? Which minigame version?

Spigot version: 1.9.2
Minigame Version: 1.14.8

> Gane you give a clear example? What excactly are you doing? When does it happen? Playing normally? Leaving by chat command? Did you leave the game or the waiting lobby?

Say I have an item in my inventory, it can be any item. Then I go to the lobby where the join signs are (same world) and click on the sign to go into the world. When I leave the sky wars match with the red stone item to quit the game and enter back into the lobby, then all my items are duplicated and every time I rejoin and leave the game the exact thing happens again.


The other bug (with the missing chunks) resets itself when you leave the server completely (without quitting minecraft itself), but happens again when you go back into the lobby (sky wars match and leave).

**Comment by mepeisen** [comment]
1) chunks:
Bugs with chunk updates after teleport are already fixed. Please retry with latest Version (1.14.10). See https://github.com/MysticCity/MinigamesAPI/issues/37
It should now correctly update the chunks on clients after porting players in 1.8 and above.

2) inventory:
I will try to reproduce this bug.

**Comment by masterhacka** [comment]
1) Could you tell me where to find these versions? I tried these but with no Luck
MinigamesLib-1.14.10-20160814.062759-2.jar
MGSkyWars-Plugin-1.14.10-20160814.063321-2.jar

2) Okay, thanks!

**Comment by mepeisen** [comment]
1) OK, then it is a new bug.
That I understand. You are using multiple worlds by which plugin? multiverse?
When exactly the worlds are changed?

**Comment by mepeisen** [comment]
newest version:
https://github.com/MysticCity/MinigamesAPI/releases/latest
https://github.com/MysticCity/MGSkyWars/releases/latest

**Comment by masterhacka** [comment]
Yes I'm using Multiverse.
The mainlobby is in the main world where you join when you get on the server. There is the join sign. Only by clicking the join sign you change to another world, where the waiting lobby and the islands for the skywars match are.
The fix with F3+A didn't work for me.

> Does it work if you do not do world hopping (having the same world for join sign, waiting lobby, arena, main Lobby)

Yes it works. If everything is in the same world everything works perfect.

**Comment by masterhacka** [comment]
Also the problem with duplicated items is solved when everything is in the same world.

**Comment by mepeisen** [comment]
Ok, last question since I do not have expeience in multiverse.
I used it locally and it did not save my inventory. Meaning: If i change the world it took the inventory with me. Is there an Option in multiverse having an individual inventory for each world? Or do you use an additional plugin for having individual inventories on each world?

**Comment by masterhacka** [comment]
I'm using "Per World Inventory" for separate Inventories.
https://www.spigotmc.org/resources/per-world-inventory.4482/
But also If I bypass the separate Inventories, I have the same issues.

**Comment by mepeisen** [comment]
please retry with latest snapshot http://nexus.xworlds.eu/nexus/content/repositories/mce-snapshots/com/github/MCE-Plugins/Minigames-All/1.14.11-SNAPSHOT/Minigames-All-1.14.11-20160817.071937-5-bin.zip
I did some minor change during teleports. This could influence your chunk bug.

**Comment by masterhacka** [comment]
Great! The chunk bug is solved! Thank you very much. The problem with duplicating items still persists.

**Comment by mepeisen** [comment]
I installed pwi but I cannot reproduce the inventory bug.
Can you give me your config.yml from pwi?

**Comment by masterhacka** [comment]
Oh sorry. I am using MultiInv... I thought I was using PWI. Sorry for this.

**Comment by mepeisen** [comment]
no problem :-)

**Comment by mepeisen** [comment]
There will be three new config options. You can change them to disable inventory, gamemode, xp reset on player leave.
But be aware that the plugin you are using is strange and out of date.
Multiverse suggest to use pvi.
You should consider updating to this plugin.

**Comment by masterhacka** [comment]
Okay, thank you very much!
